import { useEffect, useState } from 'react'
import { read,errorText } from '../client'
import { planningRange,dayLabel,addDays } from '../dateTime'
import { duration } from '../labels.uk'
import TaskCard from '../components/TaskCard'
export default function PlanningScreen({context,run,busy,onDetails,revision}) {
 const [mode,setMode]=useState(null),[employee,setEmployee]=useState(context.employee_id),[people,setPeople]=useState([]),[data,setData]=useState(null),[approvals,setApprovals]=useState([]),[recommendations,setRecommendations]=useState([]),[error,setError]=useState('')
 const range=planningRange(context.today,mode || 'week')
 useEffect(()=>{let alive=true;Promise.all([read('tasks_assignable_people',{p_permission:'tasks.read.scope'}),read('tasks_approvals')]).then(([p,a])=>{if(alive){setPeople(p);setApprovals(a)}}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[revision])
 useEffect(()=>{let alive=true;if(mode)Promise.all([read('tasks_planning',{p_employee:Number(employee),p_from:range.from,p_to:range.to}),read('tasks_recommendations',{p_employee:Number(employee)})]).then(([d,r])=>{if(alive){setData(d);setRecommendations(r);setError('')}}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[mode,employee,range.from,range.to,revision])
 return <section><h2>Планування</h2><div className="task-actions"><button aria-pressed={mode==='week'} onClick={()=>setMode('week')}>Запланувати тиждень</button><button aria-pressed={mode==='month'} onClick={()=>setMode('month')}>Запланувати місяць</button></div><p role="alert">{error}</p>
 {mode && <><label>Співробітник<select value={employee} onChange={e=>{setData(null);setEmployee(e.target.value)}}>{people.map(p=><option key={p.id} value={p.id}>{p.id===context.employee_id?'Я':p.name}</option>)}</select></label>{!data?<p role="status">Завантаження плану…</p>:<>
 {(mode==='month'?[0,1,2,3]:[0]).map(w=>{const days=mode==='month'?data.days.slice(w*7,w*7+7):data.days;return <section className="task-week" key={w}>{mode==='month' && <h3>{dayLabel(addDays(range.from,w*7))} — {dayLabel(addDays(range.from,w*7+6))} · {duration(days.reduce((n,d)=>n+d.planned_minutes,0))}</h3>}{mode==='month' ? <><p>{days.reduce((n,d)=>n+(d.task_count ?? data.tasks.filter(t=>t.planned_date===d.date).length),0)} завдань</p>{data.tasks.filter(t=>days.some(d=>d.date===t.planned_date)).map(t=><TaskCard key={t.id} task={t} context={context} onDetails={onDetails}><p>{dayLabel(t.planned_date)}</p></TaskCard>)}</> : days.map(day=>{const tasks=data.tasks.filter(t=>t.planned_date===day.date);return <section className="task-day" key={day.date}><h3>{dayLabel(day.date)}</h3><p>{day.task_count ?? tasks.length} завдань · {duration(day.planned_minutes)} / {duration(day.capacity_minutes)}{day.unknown_count>0 && ` · Без оцінки: ${day.unknown_count}`}</p><progress max={Math.max(1,day.capacity_minutes)} value={Math.min(day.planned_minutes,Math.max(1,day.capacity_minutes))} aria-label={`Завантаження ${day.date}`}/>{day.planned_minutes>day.capacity_minutes && <p className="task-warning">Перевантаження: {duration(day.planned_minutes-day.capacity_minutes)}</p>}{tasks.map(t=><TaskCard key={t.id} task={t} context={context} onDetails={onDetails}/>)}{day.date>=context.today && <button disabled={busy} onClick={()=>run('balance',{employee_id:Number(employee),date:day.date})}>Перевірити навантаження</button>}</section>})}</section>})}
 {data.next_cursor && <button disabled={busy} onClick={async()=>{try {const more=await read('tasks_planning',{p_employee:Number(employee),p_from:range.from,p_to:range.to,p_cursor:data.next_cursor});setData(old=>({...more,tasks:[...old.tasks,...more.tasks],unplanned:[...old.unplanned,...more.unplanned]}))}catch(e){setError(errorText(e))}}}>Завантажити ще завдання</button>}
 <h3>Незаплановані завдання</h3>{data.unplanned.length?data.unplanned.map(t=><TaskCard key={t.id} task={t} context={context} onDetails={onDetails}><button onClick={()=>onDetails(t)}>Запланувати</button></TaskCard>):<p>Незапланованих завдань немає.</p>}
 {recommendations.length>0 && <section><h3>Рекомендації</h3>{recommendations.map(r=><article key={r.id}><p>{r.reason}: {r.title} · {dayLabel(r.recommended_date)}</p><button disabled={busy} onClick={()=>run('recommendation_resolve',{id:r.id,decision:'approved'})}>Підтвердити</button><button disabled={busy} onClick={()=>run('recommendation_resolve',{id:r.id,decision:'rejected'})}>Відхилити</button></article>)}</section>}
 </>}</>}
 <section><h3>Очікує погодження</h3>{approvals.length?approvals.map(r=><article key={r.id}><h4>{r.title}</h4><p>{r.request_type==='reschedule'?'Перенесення':'Створення завдання'} · {r.reason}</p>{r.requested_value.planned_date && <p>Нова дата: {dayLabel(r.requested_value.planned_date)}</p>}{context.capabilities.includes('tasks.approve') && <><button disabled={busy} onClick={()=>run(r.request_type==='reschedule'?'resolve_reschedule':'resolve_approval',{request_id:r.id,decision:'approved'})}>Підтвердити</button><button disabled={busy} onClick={()=>run(r.request_type==='reschedule'?'resolve_reschedule':'resolve_approval',{request_id:r.id,decision:'rejected'})}>Відхилити</button></>}</article>):<p>Немає запитів на погодження.</p>}</section></section>
}
