import {useEffect,useState} from 'react'
import {read,errorText} from '../client'
import {addDays,dayLabel,planningRange} from '../dateTime'
import {shortDay,dateLabel} from '../planningView'
import {categoryName} from '../labels.uk'
import {actualTime,reportRange,moveReport,reportSummary,reportWeeks,exportReport} from '../reportView'
import '../workspace.css'
const kinds={planned:'Планове',unplanned:'Незаплановане',unknown:'Немає історії планування'}
export default function ReportsScreen({context,revision,onDetails}){
 const [mode,setMode]=useState('week'),[anchor,setAnchor]=useState(addDays(planningRange(context.today,'month').from,-7)),[employee,setEmployee]=useState(String(context.employee_id)),[people,setPeople]=useState(null),[snapshot,setSnapshot]=useState(null),[error,setError]=useState('')
 const range=reportRange(anchor,mode),key=JSON.stringify([employee,range.from,range.to,revision]),data=snapshot?.key===key?snapshot.rows:null
 useEffect(()=>{let alive=true;read('tasks_assignable_people',{p_permission:'tasks.report.scope'}).then(p=>{if(alive)setPeople(p)}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[])
 useEffect(()=>{let alive=true;if(!people)return;const ids=employee==='team'?people:people.filter(p=>String(p.id)===employee);Promise.all(ids.map(async p=>{const d=await read('tasks_report_activity',{p_employee:Number(p.id),p_from:range.from,p_to:range.to});return d.rows.map(r=>({...r,employee_id:p.id,employee_name:p.name}))})).then(parts=>{if(alive){setSnapshot({key,rows:parts.flat()});setError('')}}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[key,people,employee,range.from,range.to])
 const summary=reportSummary(data||[]),categories=new Map()
 for(const r of data||[]){const k=r.category_id??'other';if(!categories.has(k))categories.set(k,{name:categoryName(r.category_id,(context.category_history||context.categories)),minutes:0});categories.get(k).minutes+=Number(r.actual_minutes)}
 const lastWeek=reportRange(addDays(context.today,-7),'week'),title=mode==='month'?'Звіт за місяць':range.from===lastWeek.from?'Минулий тиждень':'Звіт за тиждень'
 const days=(from,to)=>Array.from({length:Math.round((Date.parse(to)-Date.parse(from))/86400000)+1},(_,i)=>addDays(from,i)).map(date=>{const rows=data.filter(r=>r.date===date);return <section className="report-day" key={date}><div><h3>{shortDay(date)}</h3><time dateTime={date}>{dateLabel(date)}</time><strong>{actualTime(rows.reduce((n,r)=>n+Number(r.actual_minutes),0))}</strong></div><div>{rows.length?rows.map((r,i)=><article className="report-row" key={`${r.employee_id}-${r.task_id}-${r.kind}-${i}`}><span className={`report-dot kind-${r.kind}`} aria-hidden="true"/><div><button className="report-title" onClick={()=>onDetails({id:r.task_id,title:r.title})}>{r.title}</button>{employee==='team'&&<small>{r.employee_name}</small>}</div><span className={`report-badge kind-${r.kind}`}>{kinds[r.kind]}</span><strong>{actualTime(r.actual_minutes)}</strong><span className="report-category">{categoryName(r.category_id,(context.category_history||context.categories))}</span></article>):<p className="workspace-muted">Немає записаного часу.</p>}</div></section>})
 return <section className="tasks-workspace"><h2>{title}</h2><p className="workspace-muted">Огляд виконаних задач і витраченого часу.</p><div className="workspace-toolbar"><span>{dayLabel(range.from)} — {dayLabel(range.to)}</span><button aria-label="Попередній період" onClick={()=>setAnchor(moveReport(anchor,mode,-1))}>←</button><button aria-label="Наступний період" onClick={()=>setAnchor(moveReport(anchor,mode,1))}>→</button><div role="group" aria-label="Період звіту">{[['week','Тиждень'],['month','Місяць']].map(([v,label])=><button key={v} aria-pressed={mode===v} onClick={()=>setMode(v)}>{label}</button>)}</div><button disabled={!data?.length} onClick={()=>{const blob=new Blob([exportReport(data.map(r=>({...r,category_name:categoryName(r.category_id,(context.category_history||context.categories))})))],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`zvit-${range.from}-${range.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Експортувати</button></div>
 <div className="workspace-toolbar"><div role="group" aria-label="Область звіту"><button aria-pressed={employee===String(context.employee_id)} onClick={()=>setEmployee(String(context.employee_id))}>Я</button>{people?.some(p=>p.id!==context.employee_id)&&<button aria-pressed={employee==='team'} onClick={()=>setEmployee('team')}>Команда</button>}</div><label>Співробітник<select value={employee} onChange={e=>setEmployee(e.target.value)}>{employee==='team'&&<option value="team">Команда в межах доступу</option>}{people?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><p role="alert">{error}</p>
 {!data?<p role="status">Завантаження звіту…</p>:<><div className="report-layout"><div>{mode==='week'?days(range.from,range.to):reportWeeks(range.from,range.to).map(w=><details className="report-week" key={w.from}><summary>{dayLabel(w.from)} — {dayLabel(w.to)} · {actualTime(data.filter(r=>r.date>=w.from&&r.date<=w.to).reduce((n,r)=>n+Number(r.actual_minutes),0))}</summary>{days(w.from,w.to)}</details>)}</div><aside className="report-sidebar"><section><h3>Загальний час</h3><strong className="report-total">{actualTime(summary.total)}</strong>{Object.entries(kinds).filter(([k])=>k!=='unknown'||summary.byKind.unknown>0).map(([k,label])=><p key={k}>{label}: <strong>{actualTime(summary.byKind[k])}</strong> · {summary.percent(k)}%</p>)}<small>Фактичні сесії роботи, включно з незавершеними задачами. Плановість визначена на початок кожної сесії.</small></section>
 <section><h3>Співвідношення часу</h3><div className="report-donut" role="img" aria-label={`Планове ${summary.percent('planned')}%, незаплановане ${summary.percent('unplanned')}%, невідоме ${summary.percent('unknown')}%`} style={{background:summary.total?`conic-gradient(#1769e0 0 ${summary.percent('planned')}%,#98a6bf ${summary.percent('planned')}% ${100-summary.percent('unknown')}%,#e5c47a ${100-summary.percent('unknown')}% 100%)`:'#e7edf5'}}><span>{actualTime(summary.total)}</span></div></section>
 <section><h3>Час за категоріями</h3>{[...categories.values()].sort((a,b)=>b.minutes-a.minutes).map(c=><div className="report-category-bar" key={c.name}><span>{c.name}</span><progress value={c.minutes} max={summary.total||1} aria-label={c.name}/><strong>{actualTime(c.minutes)}</strong></div>)}</section>
 <section><h3>Висновок</h3><p>{!summary.total?'За цей період немає записаного часу.':`За цей період ${summary.percent('unplanned')}% часу витрачено на незаплановані задачі.`}</p>{summary.percent('unplanned')>50&&<p>Рекомендуємо детальніше планувати операційні процеси.</p>}{summary.byKind.unknown>0&&<p>Для частини сесій немає історії планування; їх показано окремо.</p>}</section></aside></div></>}
 </section>
}
