import { useEffect,useState } from 'react'
import { read,errorText } from '../client'
import { planningRange,instantLabel } from '../dateTime'
import { statuses,duration,events } from '../labels.uk'
export default function ReportsScreen({context,revision,onDetails}) {
 const week=planningRange(context.today,'month'),[from,setFrom]=useState(week.from),[to,setTo]=useState(context.today),[employee,setEmployee]=useState(context.employee_id),[people,setPeople]=useState([]),[data,setData]=useState(null),[error,setError]=useState('')
 useEffect(()=>{let alive=true;read('tasks_assignable_people',{p_permission:'tasks.report.scope'}).then(p=>{if(alive)setPeople(p)}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[])
 useEffect(()=>{let alive=true;read('tasks_report',{p_employee:Number(employee),p_from:from,p_to:to}).then(d=>{if(alive){setData(d);setError('')}}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[employee,from,to,revision])
 return <section><h2>Рапорти</h2><div className="task-actions"><label>Співробітник<select value={employee} onChange={e=>{setData(null);setEmployee(e.target.value)}}>{people.map(p=><option value={p.id} key={p.id}>{p.id===context.employee_id?'Я':p.name}</option>)}</select></label><label>Від<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>До<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><p role="alert">{error}</p>{data && <><p>Виконано: {data.totals?.completed ?? data.tasks.filter(t=>t.status==='completed').length} · Не виконано: {data.totals?.unfinished ?? data.tasks.filter(t=>!['completed','cancelled'].includes(t.status)).length} · Перенесено: {data.totals?.moved ?? data.tasks.filter(t=>t.moved).length}</p>{data.details_truncated && <p>Підсумки охоплюють весь період. Для перегляду всіх деталей оберіть коротший період.</p>}<div className="task-table"><table><thead><tr><th>Завдання</th><th>Стан</th><th>Плановий час</th><th>Фактичний час за період</th><th>Відхилення</th></tr></thead><tbody>{data.tasks.map(t=><tr key={t.id}><td><button onClick={()=>onDetails(t)}>{t.title}</button></td><td>{statuses[t.status]}</td><td>{duration(t.estimated_minutes)}</td><td>{duration(t.period_actual_minutes)}</td><td>{t.overdue?'Прострочено':t.moved?'Перенесено':'—'}</td></tr>)}</tbody></table></div>{data.tasks.length===0 && <p>За цей період немає записів.</p>}<h3>Події та коментарі</h3><ol className="task-timeline">{data.events.map(e=><li key={e.id}>{instantLabel(e.created_at,context.settings.company_timezone)} · {events[e.event_type] || 'Зміна завдання'}{e.metadata.text && <p>{e.metadata.text}</p>}</li>)}</ol></>}</section>
}
