import { useEffect,useState } from 'react'
import { read,errorText } from '../client'
import { planningRange,dayLabel,instantLabel,localToInstant,addDays } from '../dateTime'
import { scheduleTypes } from '../labels.uk'
export default function ScheduleScreen({context,run,busy,revision}) {
 const [employee,setEmployee]=useState(context.employee_id),[people,setPeople]=useState([]),[events,setEvents]=useState([]),[error,setError]=useState(''),[offset,setOffset]=useState(0)
 const range=planningRange(addDays(context.today,offset),'month'),zone=context.settings.company_timezone
 useEffect(()=>{let alive=true;read('tasks_assignable_people',{p_permission:'tasks.read.scope'}).then(p=>{if(alive)setPeople(p)}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[])
 useEffect(()=>{let alive=true;read(employee==='team'?'tasks_team_schedule':'tasks_schedule',{...(employee==='team'?{}:{p_employee:Number(employee)}),p_from:range.from,p_to:range.to}).then(d=>{if(alive){setEvents(d);setError('')}}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[employee,range.from,range.to,revision])
 const canManage=employee!=='team' && context.capabilities.includes('tasks.schedule.manage')
 return <section><h2>Графік</h2><label>Я / команда<select value={employee} onChange={e=>{setEvents([]);setEmployee(e.target.value)}}>{people.map(p=><option value={p.id} key={p.id}>{p.id===context.employee_id?'Я':p.name}</option>)}{context.capabilities.includes('tasks.read.scope') && <option value="team">Команда</option>}</select></label><div className="task-actions"><button onClick={()=>setOffset(n=>n-28)}>Попередні тижні</button><button onClick={()=>setOffset(0)}>Сьогодні</button><button onClick={()=>setOffset(n=>n+28)}>Наступні тижні</button></div><p>Часовий пояс: {zone}</p><p role="alert">{error}</p>
 <div className="task-calendar">{Array.from({length:28},(_,i)=>addDays(range.from,i)).map(day=><article key={day}><h3>{dayLabel(day)}</h3>{events.filter(e=>new Intl.DateTimeFormat('en-CA',{timeZone:zone}).format(new Date(e.starts_at))<=day && new Intl.DateTimeFormat('en-CA',{timeZone:zone}).format(new Date(Date.parse(e.ends_at)-1))>=day).map(e=><div key={e.id}><strong>{scheduleTypes[e.type]}</strong>{e.employee_name && <p>{e.employee_name}</p>}<p>{instantLabel(e.starts_at,zone)} — {instantLabel(e.ends_at,zone)}</p>{canManage && <button disabled={busy} onClick={()=>run('schedule_delete',{employee_id:Number(employee),id:e.id,version:e.version})}>Прибрати подію</button>}</div>)}</article>)}</div>
 {canManage && <form onSubmit={async e=>{e.preventDefault();const f=e.currentTarget,v=new FormData(f);try {const ok=await run('schedule_save',{employee_id:Number(employee),type:v.get('type'),starts_at:localToInstant(v.get('start'),zone),ends_at:localToInstant(v.get('end'),zone)});if(ok)f.reset()}catch(e){setError(errorText(e))}}}><h3>Додати подію графіка</h3><label>Тип<select name="type">{Object.entries(scheduleTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Початок<input type="datetime-local" name="start" required/></label><label>Кінець<input type="datetime-local" name="end" required/></label><button disabled={busy}>Зберегти подію</button></form>}
 </section>
}
