import { useEffect,useState } from 'react'
import { read,errorText } from '../client'
export default function TaskSettingsScreen({context,people,run,busy,revision}) {
 const [admin,setAdmin]=useState(null),[error,setError]=useState(''),[scopeType,setScopeType]=useState('employee')
 useEffect(()=>{let alive=true;read('tasks_admin_state').then(d=>{if(alive)setAdmin(d)}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[revision])
 const personName=id=>people.find(p=>p.id===id)?.name || `№ ${id}`
 const submit=(action)=>e=>{e.preventDefault();run(action,Object.fromEntries([...new FormData(e.currentTarget)].map(([k,v])=>[k,v === '' ? null : v])))}
 const person=(name)=><select name={name} required>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
 return <section><h2>Налаштування роботи</h2><p role="alert">{error}</p><form onSubmit={submit('settings_save')}><label>Часовий пояс<input name="company_timezone" defaultValue={context.settings.company_timezone} required/></label><label>Типова денна місткість, хв<input name="default_daily_task_capacity_minutes" type="number" min="1" max="1440" defaultValue={context.settings.default_daily_task_capacity_minutes} required/></label><label>Горизонт планування, днів<input name="planning_horizon_days" type="number" min="7" max="366" defaultValue={context.settings.planning_horizon_days} required/></label><label>Автоматичний перенос<select name="load_balancer_enabled" defaultValue={String(context.settings.load_balancer_enabled)}><option value="false">Вимкнено — лише рекомендації</option><option value="true">Увімкнено</option></select></label><button disabled={busy}>Зберегти налаштування</button></form>
 <form onSubmit={submit('department_save')}><h3>Відділ</h3><label>Назва<input name="name" required/></label><button disabled={busy}>Додати відділ</button></form>
 <form onSubmit={submit('employee_department')}><h3>Відділ співробітника</h3><label>Співробітник{person('employee_id')}</label><label>Відділ<select name="department_id">{context.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button disabled={busy}>Призначити відділ</button></form>
 <form onSubmit={submit('reporting_save')}><h3>Підпорядкування</h3><label>Співробітник{person('employee_id')}</label><label>Керівник{person('manager_employee_id')}</label><label>Діє з<input name="effective_from" type="date" required defaultValue={context.today}/></label><button disabled={busy}>Призначити керівника</button></form>
 <form onSubmit={submit('scope_grant')}><h3>Доступ до співробітника або підлеглих</h3><label>Кому надати{person('grantee_employee_id')}</label><label>Область<select name="scope_type" value={scopeType} onChange={e=>setScopeType(e.target.value)}><option value="employee">Співробітник</option><option value="hierarchy">Співробітник та його підлеглі</option><option value="department">Відділ</option><option value="location">Локал</option></select></label>{scopeType==='department'?<label>Відділ<select name="department_id" required>{context.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>:scopeType==='location'?<label>Номер локалу<input name="location_id" type="number" min="1" required/></label>:<label>Ціль{person('target_employee_id')}</label>}<label>Дія<select name="permission">{[['tasks.assign','Призначення'],['tasks.read.scope','Перегляд'],['tasks.plan.scope','Планування'],['tasks.approve','Погодження'],['tasks.report.scope','Рапорти'],['tasks.schedule.manage','Графік']].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button disabled={busy}>Надати доступ</button></form>
 <form onSubmit={submit('capacity_save')}><h3>Особиста місткість</h3><label>Співробітник{person('employee_id')}</label><label>Діє з<input name="effective_from" type="date" required defaultValue={context.today}/></label><label>Хвилин на день<input name="daily_task_capacity_minutes" type="number" min="1" max="1440" required/></label><button disabled={busy}>Зберегти місткість</button></form>
 <form onSubmit={submit('category_save')}><h3>Категорія</h3><label>Назва<input name="name" required/></label><label>Батьківська категорія<select name="parent_id"><option value="">Без батьківської категорії</option>{context.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={busy}>Додати категорію</button></form>
 <h3>Надані дозволи</h3>{admin?.scope_grants.map(g=><article key={g.id}><p>{personName(g.grantee_employee_id)} → {g.department_id ? context.departments.find(d=>d.id===g.department_id)?.name : g.location_id ? `Локал № ${g.location_id}` : personName(g.employee_id)} · {({'tasks.assign':'Призначення','tasks.read.scope':'Перегляд','tasks.plan.scope':'Планування','tasks.approve':'Погодження','tasks.report.scope':'Рапорти','tasks.schedule.manage':'Графік'})[g.permission]}</p><button disabled={busy} onClick={()=>run('scope_revoke',{id:g.id})}>Відкликати доступ</button></article>)}
 <h3>Підпорядкування</h3>{admin?.reporting_lines.map(r=><div key={r.id}><p>{personName(r.employee_id)} → {personName(r.manager_employee_id)} · {r.effective_from} — {r.effective_to || 'без кінцевої дати'}</p>{!r.effective_to && <form onSubmit={e=>{e.preventDefault();run('reporting_end',{id:r.id,effective_to:new FormData(e.currentTarget).get('date')})}}><label>Припинити з<input name="date" type="date" required/></label><button disabled={busy}>Припинити підпорядкування</button></form>}</div>)}
 </section>
}
