import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { PGlite } from '@electric-sql/pglite'
import { validEmployee, canManageEmployee, employeeContext } from '../src/auth/session.js'

const read = path => readFile(new URL(path, import.meta.url), 'utf8')
const uid = n => `00000000-0000-0000-0000-${String(n).padStart(12, '0')}`

test('session validation never trusts legacy or mismatched employee data', () => {
  const employee = { id: 1, auth_user_id: uid(1), active: true, role: 'employee', location_id: 1 }
  assert.equal(validEmployee(employee, uid(1)), true)
  for (const change of [{ active: false }, { role: 'admin' }, { location_id: null }, { auth_user_id: uid(2) }]) {
    assert.equal(validEmployee({ ...employee, ...change }, uid(1)), false)
    assert.notEqual(employeeContext(employee), employeeContext({ ...employee, ...change }))
  }
  assert.equal(validEmployee({ id: 1, role: 'administrator' }, uid(1)), false)
  const manager = { ...employee, id: 2, role: 'manager' }
  assert.equal(canManageEmployee(manager, employee), true)
  assert.equal(canManageEmployee(manager, { ...employee, location_id: 2 }), false)
  assert.equal(canManageEmployee(manager, { ...employee, role: 'manager' }), false)
})

test('SQL migration: real PostgreSQL RLS, identity guards and employee permissions', async t => {
  const db = new PGlite()
  t.after(() => db.close())
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
    GRANT USAGE ON SCHEMA auth TO anon,authenticated,service_role;
    GRANT EXECUTE ON FUNCTION auth.uid() TO anon,authenticated,service_role;`)
  // Historical schema snapshot, not a substitute for checking the live schema before rollout.
  const audit = JSON.parse(await read('../docs/plan-items-schema-audit-result.json'))
  for (const table of audit.tables) {
    const columns = audit.columns.filter(c => c.table === table.relname).map(c =>
      `"${c.column}" ${c.type} ${c.column === 'id' ? 'GENERATED BY DEFAULT AS IDENTITY' : c.default ? `DEFAULT ${c.default}` : ''} ${c.not_null ? 'NOT NULL' : ''}`)
    await db.exec(`CREATE TABLE public."${table.relname}" (${columns.join(',')});`)
  }
  for (const c of audit.constraints) await db.exec(`ALTER TABLE public.${c.table} ADD CONSTRAINT "${c.name}" ${c.definition}`)
  for (const f of audit.functions) await db.exec(f.definition)
  // Also exercise the latest plan-item RPC overloads and delete-plan endpoint.
  await db.exec(await read('../docs/plan-items-note-time-delete-migration.sql'))
  await db.exec(`CREATE FUNCTION public.login_employee(p_pin text) RETURNS bigint LANGUAGE sql SECURITY DEFINER AS $$ SELECT 1::bigint $$;
    CREATE FUNCTION public.legacy_account_change() RETURNS void LANGUAGE sql SECURITY DEFINER AS $$ UPDATE public."Employees" SET role='administrator' $$;
    GRANT ALL ON ALL TABLES IN SCHEMA public TO anon,authenticated,service_role;
    GRANT SELECT(name) ON public."Employees" TO anon;
    CREATE POLICY old_public_read ON public."Plans" FOR SELECT USING (true);`)
  await db.exec(await read('../supabase/migrations/202609230001_auth.sql'))
  await db.exec(await read('../supabase/migrations/202609230002_auth_production.sql'))
  await db.exec(`INSERT INTO public."Locations"(id,name,active) VALUES(1,'A',true),(2,'B',true),(3,'C',true);
    INSERT INTO auth.users(id) VALUES ${[1,2,3,4,5,6,7,8,9].map(n => `('${uid(n)}')`).join(',')};
    INSERT INTO public."Employees"(id,name,role,location_id,active,auth_user_id) VALUES
      (1,'Employee A','employee',1,true,'${uid(1)}'),(2,'Manager A','manager',1,true,'${uid(2)}'),
      (3,'Chef A','su-chef',1,true,'${uid(3)}'),(4,'Admin','administrator',null,true,'${uid(4)}'),
      (5,'Employee B','employee',2,true,'${uid(5)}'),(6,'Disabled','employee',1,false,'${uid(6)}'),
      (7,'Pending','employee',1,true,null),(8,'Other manager','manager',1,true,'${uid(8)}');
    SELECT setval(pg_get_serial_sequence('public."Employees"','id'),100);
    INSERT INTO public."Plans"(id,location_id,plan_date,status) VALUES
      (1,1,(now() AT TIME ZONE 'Europe/Warsaw')::date,'active'),
      (2,2,(now() AT TIME ZONE 'Europe/Warsaw')::date,'active'),
      (3,1,(now() AT TIME ZONE 'Europe/Warsaw')::date-1,'completed'),
      (4,1,(now() AT TIME ZONE 'Europe/Warsaw')::date+8,'active');
    INSERT INTO public."Plan_items"(id,plan_id,nazwa,ilosc,jednostka) VALUES(1,1,'A',1,'kg'),(2,2,'B',1,'kg');`)
  const as = async (n, role = 'authenticated') => {
    await db.exec(`RESET ROLE; SELECT set_config('request.jwt.claim.sub','${n ? uid(n) : ''}',false); SET ROLE ${role};`)
  }
  const rows = async sql => (await db.query(sql)).rows
  const denied = async sql => assert.rejects(db.query(sql))
  await as(null, 'anon')
  await denied('SELECT * FROM public."Plans"')
  await denied('SELECT name FROM public."Employees"')
  await denied("SELECT public.login_employee('1234')")
  await denied('SELECT public.legacy_account_change()')
  await as(1)
  assert.deepEqual((await rows('SELECT id FROM public."Plans" ORDER BY id')).map(x => x.id), [1])
  assert.deepEqual((await rows('SELECT id FROM public."Plan_items" ORDER BY id')).map(x => x.id), [1])
  await denied('SELECT pin_hash FROM public."Employees"')
  await denied('SELECT app_private.actor()')
  await denied('SELECT public.auth_list_employees()')
  await denied('SELECT public.complete_production_plan(2,1)') // impersonated manager
  await denied('SELECT public.delete_production_plan(2,1)')
  await denied('SELECT public.complete_production_plan(1,1)') // actual employee
  await denied('SELECT public.start_plan_item(1,2)') // another location
  await denied('UPDATE public."Plan_items" SET gotowe=true WHERE id=1')
  await denied("SELECT public.auth_employee_names(2,ARRAY[1]::bigint[])")
  await denied(`SELECT public.auth_link_employee('${uid(4)}',7,'${uid(7)}')`)
  await rows('SELECT public.start_plan_item(1,1)')
  await denied('SELECT public.start_plan_item(1,1)')
  await rows('SELECT public.complete_plan_item(1,1)')
  assert.equal((await rows('SELECT employee_id FROM public."Plan_items" WHERE id=1'))[0].employee_id,1)
  await denied('SELECT public.complete_plan_item(1,1)')
  await as(2)
  assert.equal((await rows('SELECT * FROM public.auth_employee_names(2,ARRAY[1,5]::bigint[])')).length,1)
  assert.equal((await rows('SELECT * FROM public.auth_list_employees()')).some(x => x.id === 5), false)
  await denied("SELECT public.auth_save_employee(1,'Promoted','administrator',1,true)")
  await denied("SELECT public.auth_save_employee(5,'Other location','employee',1,true)")
  await denied("SELECT public.auth_save_employee(8,'Other manager','employee',1,true)")
  await rows("SELECT public.auth_save_employee(1,'Employee A','su-chef',1,true)")
  await rows("SELECT public.auth_save_employee(NULL,'New','employee',1,true)")
  await as(3)
  await denied("SELECT public.auth_save_employee(NULL,'New','employee',1,true)")
  await rows('SELECT public.complete_production_plan(3,1)')
  await as(6)
  assert.equal((await rows('SELECT * FROM public.auth_employee_profile()')).length,0)
  assert.equal((await rows('SELECT * FROM public."Plans"')).length,0)
  await denied('SELECT public.start_plan_item(6,1)')
  await as(9) // authenticated but unlinked
  assert.equal((await rows('SELECT * FROM public."Plans"')).length,0)
  await as(4)
  assert.equal((await rows('SELECT * FROM public."Plans"')).length,4)
  await rows('SELECT public.start_plan_item(4,2)') // global admin, no assigned location
  await rows('SELECT public.complete_plan_item(4,2)')
  await denied("SELECT public.auth_save_employee(4,'Admin','employee',1,false)") // no self-edit
  await rows("SELECT public.auth_save_employee(2,'Manager A','manager',1,false)")
  await as(2)
  await denied('SELECT public.complete_production_plan(2,1)') // old token, current disabled flag
  await as(null,'service_role')
  await denied(`SELECT public.auth_link_employee('${uid(8)}',5,'${uid(7)}')`)
  await rows(`SELECT public.auth_link_employee('${uid(4)}',7,'${uid(7)}')`)
  await denied(`SELECT public.auth_link_employee('${uid(4)}',7,'${uid(9)}')`)
  await as(7)
  assert.equal((await rows('SELECT * FROM public.auth_employee_profile()'))[0].id,7)
})
