import {test} from 'node:test'
import assert from 'node:assert/strict'
import {randomUUID} from 'node:crypto'
import {graphLayout,processSteps,patchTask,removeTask,wizardDraft,requiredRoles} from '../src/tasks/processes/model.js'
const graph=()=>{const ids=Array.from({length:10},()=>randomUUID()),pairs=[[1,2],[2,3],[2,4],[2,5],[3,6],[4,6],[5,6],[6,7],[6,8],[7,9],[8,9],[9,10]];return {stages:[{key:randomUUID(),name:'Stage',tasks:ids.map((key,i)=>({key,title:`2.${i+1}`,depends_on:pairs.filter(([,b])=>b===i+1).map(([a])=>ids[a-1])}))}]}}
test('critical graph exact seven levels; every edge and arrow endpoint flows down',()=>{const doc=graph(),g=graphLayout(doc);assert.deepEqual(g.rows.map(row=>row.map(t=>t.title)),[['2.1'],['2.2'],['2.3','2.4','2.5'],['2.6'],['2.7','2.8'],['2.9'],['2.10']]);for(const e of g.edges){const a=g.nodes.find(t=>t.key===e.from),b=g.nodes.find(t=>t.key===e.to);assert.ok(b.y>a.y+88)}for(const row of g.rows){const ns=g.nodes.filter(n=>n.level===g.nodes.find(n=>n.key===row[0].key).level);for(let i=1;i<ns.length;i++)assert.ok(ns[i].x>=ns[i-1].x+250)}})
test('insert/reorder changes display numbers, never dependency UUIDs',()=>{const doc=graph(),last=structuredClone(doc.stages[0].tasks.at(-1));doc.stages[0].tasks.splice(1,0,{key:randomUUID(),title:'Inserted',depends_on:[]});assert.equal(processSteps(doc).at(-1).number,'1.11');assert.deepEqual(doc.stages[0].tasks.at(-1),last);assert.equal(graphLayout(doc).nodes.length,11)})
test('self, cycle and invalid references fail graph layout',()=>{for(const kind of ['self','cycle','missing']){const doc=graph(),tasks=doc.stages[0].tasks;tasks[0].depends_on=[kind==='self'?tasks[0].key:kind==='cycle'?tasks.at(-1).key:randomUUID()];assert.throws(()=>graphLayout(doc),/DEPENDENCY/)}})
test('parallel roots have no implicit order and empty draft works',()=>{const doc={stages:[{key:'s',tasks:[{key:'a'},{key:'b'}]}]};assert.equal(graphLayout(doc).rows.length,1);assert.equal(graphLayout({stages:[]}).nodes.length,0)})
test('editor changes share one model and removal cleans references',()=>{const doc=graph(),key=doc.stages[0].tasks[1].key,next=patchTask(doc,key,{title:'Changed'});assert.equal(next.stages[0].tasks[1].title,'Changed');assert.notEqual(doc.stages[0].tasks[1].title,'Changed');assert.doesNotThrow(()=>graphLayout(removeTask(doc,key)))})
test('legacy draft conversion preserves UUIDs and references, never changes source',()=>{const doc=graph();doc.owner_employee_id=1;doc.stages[0].tasks[0].assigned_to_employee_id=1;const next=wizardDraft(doc);assert.equal(next.stages[0].tasks[0].key,doc.stages[0].tasks[0].key);assert.equal(next.owner_employee_id,undefined);assert.equal(next.stages[0].tasks[0].assigned_to_employee_id,undefined);assert.equal(doc.owner_employee_id,1);assert.doesNotThrow(()=>graphLayout(next))})
test('launch collects distinct owner, involved, R/A/C/I roles',()=>{assert.deepEqual(requiredRoles({responsible_role:'manager',involved_roles:['director'],stages:[{tasks:[{responsible_role:'expert',raci:{accountable:[{type:'role',id:'director'}],informed:[{type:'role',id:'specialist'}]}}]}]}),['manager','director','expert','specialist'])})
