import EmailInvite from '../../auth/EmailInvite'
import {useEffect,useState} from 'react'
import {read,errorText} from '../client'
import Dialog from '../components/Dialog'
import {adminTabs,systemRoles,productionRoles,roleName,capabilityName} from './labels'
import Processes from './Processes'
import TaskSettingsScreen from '../screens/TaskSettingsScreen'
export default function AdminScreen(props){
 const {context,run,busy,revision}=props,[tab,setTab]=useState('employees'),[data,setData]=useState(null),[error,setError]=useState(''),[edit,setEdit]=useState(null),[category,setCategory]=useState(null),[filters,setFilters]=useState({department:'',role:'',active:''})
 useEffect(()=>{let live=true;read('tasks_admin_directory').then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(errorText(e))});return()=>{live=false}},[revision])
 if(!context.capabilities.includes('tasks.admin'))return null
 const employee=id=>data?.employees.find(e=>e.id===id)?.name||'Не призначено',manager=id=>data?.reporting_lines.find(r=>r.employee_id===id&&r.effective_from<=context.today&&(!r.effective_to||r.effective_to>context.today))?.manager_employee_id
 return <section className="task-admin"><h2>Адмін панель</h2><nav aria-label="Адміністрування">{Object.entries(adminTabs).map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</nav><p role="alert">{error}</p>{!data?<p role="status">Завантаження…</p>:<>
 {tab==='employees'&&<><div className="admin-toolbar"><h3>Працівники</h3><button className="primary" onClick={()=>setEdit({name:'',role:'specialist',active:true,production_role:null})}>Додати працівника</button></div><div className="admin-filters"><label>Відділ<select aria-label="Відділ" value={filters.department} onChange={e=>setFilters({...filters,department:e.target.value})}><option value="">Усі відділи</option>{data.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Роль у системі<select aria-label="Роль у системі" value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}><option value="">Усі ролі</option>{Object.entries({...systemRoles,...productionRoles}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Статус<select aria-label="Статус" value={filters.active} onChange={e=>setFilters({...filters,active:e.target.value})}><option value="">Усі</option><option value="true">Активні</option><option value="false">Неактивні</option></select></label></div>
 <div className="admin-table-wrap"><table><thead><tr>{["Ім’я",'Статус','Відділ','Виробнича роль','Роль у системі','Керівник','Локація','Дії'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.employees.filter(e=>(!filters.department||String(e.department_id)===filters.department)&&(!filters.role||e.role===filters.role)&&(!filters.active||String(e.active)===filters.active)).map(e=><tr key={e.id}><td>{e.name}<EmailInvite employee={e} revision={revision}/></td><td>{e.archived?'Архівний':e.active?'Активний':'Неактивний'}</td><td>{data.departments.find(d=>d.id===e.department_id)?.name||'Не призначено'}</td><td>{productionRoles[e.production_role]||'Не призначено'}</td><td>{roleName(e.role)}</td><td>{employee(manager(e.id))}</td><td>{data.locations.find(l=>l.id===e.location_id)?.name||'Не призначено'}</td><td><button disabled={e.id===context.employee_id||e.archived} onClick={()=>setEdit({...e,manager_id:manager(e.id)})}>Редагувати</button></td></tr>)}</tbody></table></div></>}
 {tab==='structure'&&<><h3>Структура</h3><div className="admin-grid">{data.departments.map(d=><article key={d.id}><h4>{d.name}</h4>{data.employees.filter(e=>e.department_id===d.id).map(e=><p key={e.id}>{e.name} · {employee(manager(e.id))}</p>)}</article>)}</div><details><summary>Налаштування структури та планування</summary><TaskSettingsScreen {...props}/></details></>}
 {tab==='access'&&<><h3>Доступи</h3><p>Перегляд чинних ролей і областей доступу. Виробнича роль не надає дозволів.</p>{data.employees.map(e=><details key={e.id}><summary>{e.name} · {roleName(e.role)}</summary><ul>{e.capabilities.map(c=><li key={c}>{capabilityName(c)}</li>)}</ul>{data.scope_grants.filter(g=>g.grantee_employee_id===e.id).map(g=><p key={g.id}>{capabilityName(g.permission)} · {g.department_id?data.departments.find(d=>d.id===g.department_id)?.name:g.location_id?data.locations.find(l=>l.id===g.location_id)?.name:employee(g.employee_id)}</p>)}<p>Керівник: {employee(manager(e.id))}</p></details>)}</>}
 {tab==='dictionaries'&&<><div className="admin-toolbar"><h3>Категорії завдань</h3><button onClick={()=>setCategory({name:'',sort_order:0,active:true})}>Додати категорію</button></div>{data.categories.map(c=><article className="dictionary-row" key={c.id}><div>{c.parent_id&&<small>{data.categories.find(p=>p.id===c.parent_id)?.name} → </small>}<strong>{c.name}</strong><small>{c.active?'Активна':'Неактивна'} · Порядок: {c.sort_order}</small></div><button onClick={()=>setCategory(c)}>Редагувати</button><button disabled={busy} onClick={()=>run('category_save',{id:c.id,name:c.name,parent_id:c.parent_id,sort_order:c.sort_order,active:!c.active})}>{c.active?'Деактивувати':'Відновити'}</button></article>)}<p>Неактивні категорії залишаються в історичних завданнях.</p></>}
 {tab==='processes'&&<Processes {...props} directory={data}/>}
 {edit&&<Dialog title={edit.id?'Редагувати працівника':'Додати працівника'} busy={busy} onClose={()=>setEdit(null)}><form onSubmit={async e=>{e.preventDefault();if(await run('admin_employee_save',{id:edit.id||null,name:edit.name,role:edit.role,active:edit.active,location_id:edit.location_id||null,department_id:edit.department_id||null,production_role:edit.production_role||null,manager_id:edit.manager_id||null}))setEdit(null)}}>
 <label>Ім’я<input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Відділ<select aria-label="Відділ" value={edit.department_id||''} onChange={e=>setEdit({...edit,department_id:Number(e.target.value)||null,production_role:null})}><option value="">Не призначено</option>{data.departments.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
 {data.departments.find(d=>d.id===edit.department_id)?.code==='production'&&<label>Виробнича роль<select aria-label="Виробнича роль" value={edit.production_role||''} onChange={e=>setEdit({...edit,production_role:e.target.value||null})}><option value="">Не призначено</option>{Object.entries(productionRoles).filter(([k])=>k!=='employee').map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}
 <label>Роль у системі<select aria-label="Роль у системі" value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}>{!systemRoles[edit.role]&&<option value={edit.role}>{roleName(edit.role)} — чинна успадкована роль</option>}{Object.entries(systemRoles).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><small>Це поле визначає дозволи. Зміна застосовується лише після збереження.</small>
 <label>Керівник<select aria-label="Керівник" value={edit.manager_id||''} onChange={e=>setEdit({...edit,manager_id:Number(e.target.value)||null})}><option value="">Не призначено</option>{data.employees.filter(e=>e.active&&!e.archived&&e.id!==edit.id).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Локація / приміщення<select aria-label="Локація / приміщення" value={edit.location_id||''} onChange={e=>setEdit({...edit,location_id:Number(e.target.value)||null})}><option value="">Не призначено</option>{data.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/>Активний працівник</label><button className="primary" disabled={busy}>Зберегти</button></form></Dialog>}
 {category&&<Dialog title="Категорія завдань" onClose={()=>setCategory(null)} busy={busy}><form onSubmit={async e=>{e.preventDefault();if(await run('category_save',{...category,parent_id:category.parent_id||null}))setCategory(null)}}><label>Назва<input required value={category.name} onChange={e=>setCategory({...category,name:e.target.value})}/></label><label>Батьківська категорія<select aria-label="Батьківська категорія" value={category.parent_id||''} onChange={e=>setCategory({...category,parent_id:Number(e.target.value)||null})}><option value="">Без батьківської категорії</option>{data.categories.filter(c=>c.id!==category.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Порядок<input type="number" value={category.sort_order} onChange={e=>setCategory({...category,sort_order:Number(e.target.value)})}/></label><button disabled={busy}>Зберегти</button></form></Dialog>}
 </> }</section>
}
