import {useId,useState} from 'react'
import {processSteps,dependencyEdges,canConnect} from './model'
import {P} from './labels'
export default function Dependencies({doc,onChange,disabled}){
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[error,setError]=useState(''),[drag,setDrag]=useState(null),marker=useId().replaceAll(':','')
 const steps=processSteps(doc),edges=dependencyEdges(doc)
 const connect=(a,b)=>{if(disabled)return;if(!canConnect(doc,a,b)){setError(P.invalidEdge);return}onChange({...doc,stages:doc.stages.map(s=>({...s,tasks:s.tasks.map(t=>t.key===b?{...t,depends_on:[...(t.depends_on||[]),a]}:t)}))});setError('');setDrag(null)}
 return <section className="process-dependencies"><p>{P.dependencyHelp}</p><p role="alert">{error}</p><div className="dependency-canvas" role="region" aria-label={P.dependencies} tabIndex={0}><div style={{position:'relative',width:620,minHeight:Math.max(100,steps.length*86)}}>
 <svg aria-hidden="true" width="620" height={Math.max(100,steps.length*86)} className="dependency-lines"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="black"/></marker></defs>{edges.map(e=>{const a=steps.findIndex(t=>t.key===e.from),b=steps.findIndex(t=>t.key===e.to);return a<0||b<0?null:<path key={`${e.from}-${e.to}`} d={`M480 ${a*86+34} C600 ${a*86+34},600 ${b*86+34},480 ${b*86+34}`} fill="none" stroke="black" strokeWidth="2" markerEnd={`url(#${marker})`}/>})}</svg>
 {steps.map((t,i)=><div className="dependency-node" key={t.key} style={{top:i*86}}><span>{t.number} · {t.title}</span><button type="button" disabled={disabled} aria-label={`Вхід: ${t.title}`} onPointerUp={()=>{if(drag)connect(drag,t.key)}} onClick={()=>setTo(t.key)}>←</button><button type="button" disabled={disabled} aria-label={`Вихід: ${t.title}`} onPointerDown={e=>{e.preventDefault();if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);setDrag(t.key);setFrom(t.key)}} onClick={()=>setFrom(t.key)}>→</button></div>)}</div></div>
 <div className="admin-grid"><label>{P.source}<select aria-label={P.source} value={from} disabled={disabled} onChange={e=>setFrom(e.target.value)}><option value="">{P.none}</option>{steps.map(t=><option key={t.key} value={t.key}>{t.number} {t.title}</option>)}</select></label><label>{P.target}<select aria-label={P.target} value={to} disabled={disabled} onChange={e=>setTo(e.target.value)}><option value="">{P.none}</option>{steps.map(t=><option key={t.key} value={t.key}>{t.number} {t.title}</option>)}</select></label><button type="button" disabled={disabled||!from||!to} onClick={()=>connect(from,to)}>{P.connect}</button></div>
 <ul>{edges.map(e=><li key={`${e.from}-${e.to}`}>{steps.find(t=>t.key===e.from)?.title} → {steps.find(t=>t.key===e.to)?.title} {e.implicit?<small>{P.implicit}</small>:<button type="button" disabled={disabled} aria-label={`${P.removeEdge}: ${e.from} → ${e.to}`} onClick={()=>onChange({...doc,stages:doc.stages.map(s=>({...s,tasks:s.tasks.map(t=>t.key===e.to?{...t,depends_on:t.depends_on.filter(k=>k!==e.from)}:t)}))})}>×</button>}</li>)}</ul></section>
}
