import {useState} from 'react'
import {dateLabel} from '../dateTime'
import {isFinished,processProgress} from './model'
import {P} from './labels'
export default function ProcessList({data,tab,directory,context,busy,run,setEditor,setLaunch,setInstance}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[owner,setOwner]=useState(''),[sort,setSort]=useState('name'),[launchType,setLaunchType]=useState('')
 const rows=(tab==='templates'?data.templates.map(t=>{const versions=data.versions.filter(v=>v.template_id===t.id).sort((a,b)=>a.number-b.number),latest=versions.at(-1);return latest?{...t,versions,latest,published:versions.filter(v=>v.status==='published').at(-1),doc:latest.definition}:null}).filter(Boolean):data.instances.filter(i=>isFinished(i)===(tab==='done')).map(i=>({...i,doc:data.versions.find(v=>v.id===i.version_id)?.definition||{stages:[]}})))
 .filter(r=>`${r.name} ${r.doc.description||''}`.toLocaleLowerCase('uk').includes(search.toLocaleLowerCase('uk'))&&(!category||String(r.doc.category_id)===category)&&(!owner||String(r.owner_employee_id||r.doc.owner_employee_id)===owner)&&(!launchType||launchType==='manual'))
 .sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'uk'):String(b.latest?.updated_at||b.latest?.created_at||b.created_at||'').localeCompare(String(a.latest?.updated_at||a.latest?.created_at||a.created_at||'')))
 const canManage=context.capabilities.includes('processes.manage')
 return <><div className="admin-filters"><label>{P.search}<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>{P.category}<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">{P.allCategories}</option>{directory.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{P.owner}<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">{P.allOwners}</option>{directory.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Тип запуску<select value={launchType} onChange={e=>setLaunchType(e.target.value)}><option value="">{P.allLaunch}</option><option value="manual">{P.manual}</option></select></label><label>{P.sort}<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">{P.byName}</option><option value="updated">{P.byUpdated}</option></select></label></div>
 <div className="admin-table-wrap" role="region" aria-label={P.title} tabIndex={0}><table className="process-list"><thead><tr>{[P.name,P.category,'Тип запуску',P.owner,P.description,P.stages,P.tasks,P.updated,P.actions].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="process-summary"><td><h4>{r.name}</h4>{r.latest?<small>Версія {r.latest.number} · {r.latest.status==='draft'?'Чернетка':'Опублікована'}</small>:<small>{processProgress(r.tasks)}% · {dateLabel(r.starts_on)}</small>}</td><td>{directory.categories.find(c=>c.id===r.doc.category_id)?.name||'—'}</td><td>{P.manual}</td><td>{directory.employees.find(e=>e.id===(r.owner_employee_id||r.doc.owner_employee_id))?.name||P.none}</td><td>{r.doc.description||'—'}</td><td>{r.doc.stages.length}</td><td>{r.tasks?.length??r.doc.stages.reduce((n,s)=>n+s.tasks.length,0)}</td><td>{(r.latest?.updated_at||r.latest?.created_at||r.created_at)?dateLabel((r.latest?.updated_at||r.latest?.created_at||r.created_at).slice(0,10)):'—'}</td><td><div className="process-row-actions"><button onClick={()=>setInstance(r.latest?{...r,template:true,version_id:r.latest.id}:r)}>{r.latest?P.open:'Переглянути процес'}</button>{r.latest&&<>{canManage&&<button onClick={()=>setEditor(r.latest)}>{r.latest.status==='draft'?'Редагувати':'Переглянути'}</button>}<button disabled={!r.published||busy||!context.capabilities.includes('processes.launch')} onClick={()=>setLaunch({version_id:r.published.id,starts_on:context.today,default_employee_id:context.employee_id,assignments:{},versions:r.versions.filter(v=>v.status==='published')})}>Запустити</button>{canManage&&<details><summary aria-label={`Дії: ${r.name}`}>…</summary>{[['process_duplicate','Дублювати'],['process_version','Нова версія']].map(([action,label])=><button key={action} disabled={busy} onClick={async()=>{const result=await run(action,{version_id:r.latest.id});if(result)setEditor({id:result.version_id,revision:1,definition:structuredClone(r.doc),status:'draft'})}}>{label}</button>)}</details>}</>}</div></td></tr>)}</tbody></table>{!rows.length&&<p>{P.empty}</p>}</div></>
}
