import {useId,useRef,useState} from 'react'
import {graphLayout,durationText} from './model'
import {roleName} from '../admin/labels'
export default function ProcessDiagram({doc,selected,onSelect,onAddStage,onAddTask,disabled,employees=[]}){
 const [zoom,setZoom]=useState(1),[pan,setPan]=useState(false),[collapsed,setCollapsed]=useState([]),ref=useRef(),drag=useRef(),marker=useId().replaceAll(':','');let graph,error
 try{graph=graphLayout(doc)}catch(e){error=e.message}
 if(error)return <p role="alert">Залежності містять цикл або невідоме завдання.</p>
 const {nodes,edges,width,height}=graph,point=id=>nodes.find(t=>t.key===id),path=(a,b)=>`M${a.x+125},${a.y+88} V${b.y-14} H${b.x+125} V${b.y}`
 return <section className="process-diagram" ref={ref}><div className="process-graph-tools"><button type="button" disabled={disabled} onClick={onAddStage}>＋ Додати етап</button><button type="button" aria-pressed={!pan} onClick={()=>setPan(false)}>Вибір</button><button type="button" aria-pressed={pan} onClick={()=>setPan(true)}>Переміщення</button><button type="button" aria-label="Зменшити" onClick={()=>setZoom(Math.max(.3,zoom-.1))}>−</button><output>{Math.round(zoom*100)}%</output><button type="button" aria-label="Збільшити" onClick={()=>setZoom(Math.min(2,zoom+.1))}>＋</button><button type="button" onClick={()=>setZoom(Math.min(1,(ref.current.clientWidth-32)/width))}>Вмістити</button><button type="button" onClick={()=>{setZoom(1);setCollapsed([])}}>Автовирівнювання</button><button type="button" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else ref.current.requestFullscreen?.()}}>На весь екран</button></div>
 <div className={`process-graph-scroll ${pan?'is-pan':''}`} onPointerDown={e=>{if(!pan)return;drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;e.currentTarget.scrollLeft=drag.current.left+drag.current.x-e.clientX;e.currentTarget.scrollTop=drag.current.top+drag.current.y-e.clientY}} onPointerUp={()=>{drag.current=null}}><div style={{width:width*zoom,height:height*zoom}}><div className="process-graph-canvas" style={{width,height,transform:`scale(${zoom})`}}>
 <div className="process-terminal start" style={{left:width/2-85}}>▶ Початок</div>
 {graph.bands.map(band=>{const stages=doc.stages.filter(s=>band.stageKeys.includes(s.key));return <div className={`process-graph-band stage-tone-${doc.stages.indexOf(stages[0])%4}`} key={band.key} style={{top:band.top,width,height:band.height}}><div className="process-band-heading">{stages.map(s=><div key={s.key}><strong>{doc.stages.indexOf(s)+1}. {s.name}</strong><small>{s.description} · {s.tasks.length} завдань</small><button type="button" disabled={disabled} onClick={()=>onAddTask(s.key)}>＋ Додати завдання</button><button type="button" aria-label={`Згорнути ${s.name}`} aria-expanded={!collapsed.includes(s.key)} onClick={()=>setCollapsed(collapsed.includes(s.key)?collapsed.filter(k=>k!==s.key):[...collapsed,s.key])}>⌃</button></div>)}</div></div>})}
 <svg className="process-graph-edges" width={width} height={height} aria-label="Зв’язки зверху вниз"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="4" refY="7" orient="0"><path d="M0 0 L4 8 L8 0" fill="#36445e"/></marker></defs>{edges.map(e=><path key={`${e.from}-${e.to}`} data-from={e.from} data-to={e.to} d={path(point(e.from),point(e.to))} markerEnd={`url(#${marker})`}/>)}{nodes.filter(t=>!edges.some(e=>e.to===t.key)).map(t=><path key={`start-${t.key}`} d={`M${width/2} 42 V${t.y-14} H${t.x+125} V${t.y}`} markerEnd={`url(#${marker})`}/>)}{nodes.filter(t=>!edges.some(e=>e.from===t.key)).map(t=><path key={`end-${t.key}`} d={`M${t.x+125} ${t.y+88} V${height-60} H${width/2} V${height-35}`} markerEnd={`url(#${marker})`}/>)}</svg>
 {nodes.map(t=><button type="button" key={t.key} data-task-key={t.key} data-level={t.level} className={`process-graph-node ${selected===t.key?'selected':''}`} style={{left:t.x,top:t.y}} onClick={()=>onSelect(t.key)}><b>{t.number}　{t.icon||'▤'}　{t.title}</b>{!collapsed.includes(t.stageKey)&&<><small>{employees.find(e=>e.id===t.assigned_to_employee_id)?.name||roleName(t.responsible_role)}</small><small>◷ {durationText(t)}</small></>}</button>)}
 <div className="process-terminal end" style={{left:width/2-85,top:height-35}}>■ Завершення</div></div></div></div></section>
}
