import {useState} from 'react'
import {dateLabel} from '../dateTime'
import {isFinished,processProgress} from './model'
import {roleName} from '../admin/labels'
import {P} from './labels'
function instanceStatus(i){if(isFinished(i))return i.tasks.every(t=>t.status==='completed')?'completed':'cancelled';if(i.tasks.some(t=>t.waiting_confirmation))return 'review';if(i.deadline&&i.deadline<new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Warsaw'}))return 'late';if(i.tasks.some(t=>t.priority==='critical'&&t.blocked))return 'risk';return 'active'}
const statuses={completed:'Завершено',cancelled:'Скасовано',review:'На перевірці',late:'Відстає',risk:'Ризик',active:'Виконується'}
export default function ProcessList({data,tab,directory,context,busy,run,setEditor,setLaunch,setInstance}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[owner,setOwner]=useState(''),[sort,setSort]=useState('name'),[launchType,setLaunchType]=useState(''),[status,setStatus]=useState(''),[rating,setRating]=useState(''),[grid,setGrid]=useState(false),[archived,setArchived]=useState(false)
 const finished=i=>i.finished_at||(i.tasks||[]).map(t=>t.completed_at).filter(Boolean).sort().at(-1)||i.created_at
 const all=tab==='templates'?data.templates.filter(t=>archived||t.active!==false).map(t=>{const versions=data.versions.filter(v=>v.template_id===t.id).sort((a,b)=>a.number-b.number),latest=versions.at(-1);return latest?{...t,versions,latest,published:versions.filter(v=>v.status==='published').at(-1),doc:latest.definition}:null}).filter(Boolean):data.instances.filter(i=>isFinished(i)===(tab==='done')).map(i=>({...i,doc:i.execution_snapshot||data.versions.find(v=>v.id===i.version_id)?.definition||{stages:[]}}))
 const rows=all.filter(r=>`${r.name} ${r.doc.description||''} ${r.doc.goal||''}`.toLocaleLowerCase('uk').includes(search.toLocaleLowerCase('uk'))&&(!category||String(r.doc.category_id)===category)&&(!owner||String(tab==='templates'?(r.doc.responsible_role||r.doc.owner_employee_id):r.owner_employee_id)===owner)&&(tab!=='templates'||!launchType||(r.doc.launch_type||'manual')===launchType)&&(tab!=='active'||!status||instanceStatus(r)===status)&&(tab!=='done'||!rating||Number(r.rating)===Number(rating))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'uk'):String(tab==='done'?finished(b):tab==='active'?b.starts_on:b.latest?.updated_at||b.latest?.created_at||'').localeCompare(String(tab==='done'?finished(a):tab==='active'?a.starts_on:a.latest?.updated_at||a.latest?.created_at||'')))
 const canManage=context.capabilities.includes('processes.manage'),owners=tab==='templates'?(data.roles||[]).map(r=>({id:r,name:roleName(r)})):directory.employees
 const headers=tab==='templates'?['#',P.name,'Категорія','Тип запуску','Відповідальний',P.description,P.stages,P.tasks,'Останнє оновлення',P.actions]:tab==='active'?['#',P.name,'Категорія','Відповідальний','Дата початку','Дедлайн','Прогрес','Статус',P.actions]:['#',P.name,'Категорія','Відповідальний','Дата початку','Дата завершення','Тривалість','Оцінка','Статус',P.actions]
 const launch=r=>setLaunch({version_id:r.published.id,starts_on:context.today,default_employee_id:context.employee_id,assignments:{},versions:r.versions.filter(v=>v.status==='published')})
 const actions=r=><div className="process-row-actions"><button type="button" onClick={()=>setInstance(r.latest?{...r,template:true,version_id:r.latest.id}:r)}>{r.latest?'Переглянути':'Відкрити'}</button>{r.latest&&<><button disabled={r.active===false||!r.published||busy||!context.capabilities.includes('processes.launch')} onClick={()=>launch(r)}>▷ Запустити</button>{canManage&&<details><summary aria-label={`Дії: ${r.name}`}>⋮</summary><div className="process-options"><button disabled={busy} onClick={async()=>{if(r.latest.status==='draft')setEditor(r.latest);else{const result=await run('process_version',{version_id:r.latest.id});if(result)setEditor({id:result.version_id,revision:1,definition:structuredClone(r.doc),status:'draft'})}}}>Редагувати</button><button disabled={busy} onClick={async()=>{const result=await run('process_duplicate',{version_id:r.latest.id});if(result)setEditor({id:result.version_id,revision:1,definition:structuredClone(r.doc),status:'draft'})}}>Дублювати</button><button disabled={busy||r.active===false} onClick={()=>{if(window.confirm('Архівувати шаблон? Історія та активні процеси залишаться.'))run('process_archive',{template_id:r.id})}}>Архівувати</button></div></details>}</>}</div>
 return <><div className="process-filters"><input type="search" aria-label={P.search} placeholder="Пошук за назвою, описом…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Категорія" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Усі категорії</option>{directory.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Відповідальний" value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Усі власники</option>{owners.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select>{tab==='templates'?<><select aria-label="Тип запуску" value={launchType} onChange={e=>setLaunchType(e.target.value)}><option value="">Усі типи запуску</option><option value="manual">Вручну</option><option value="automatic">Автоматично</option></select><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Архівні</label></>:tab==='active'?<select aria-label="Статус" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Усі статуси</option>{['active','late','risk','review'].map(s=><option key={s} value={s}>{statuses[s]}</option>)}</select>:<select aria-label="Оцінка" value={rating} onChange={e=>setRating(e.target.value)}><option value="">Усі оцінки</option>{Array.from({length:9},(_,i)=>1+i*.5).map(n=><option key={n}>{n}</option>)}</select>}<select aria-label="Сортування" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">За назвою</option><option value="date">{tab==='done'?'За датою завершення':tab==='active'?'За датою початку':'За оновленням'}</option></select><button aria-label="Список" aria-pressed={!grid} onClick={()=>setGrid(false)}>☷</button><button aria-label="Картки" aria-pressed={grid} onClick={()=>setGrid(true)}>▦</button></div>
 <div className={`admin-table-wrap ${grid?'process-grid-view':''}`} role="region" aria-label={P.title} tabIndex={0}><table className="process-list"><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,index)=>{const end=finished(r),progress=processProgress(r.tasks||[]);return <tr key={r.id} className="process-summary"><td>{index+1}</td><td><h4><span className="process-icon">▤</span>{r.name}</h4><small>{r.latest?(r.active===false?'Архівний':r.latest.status==='draft'?'Чернетка':'Активний'):r.doc.name}</small></td><td><span className={`process-category category-${(r.doc.category_id||0)%7}`}>{directory.categories.find(c=>c.id===r.doc.category_id)?.name||'Без категорії'}</span></td>{tab==='templates'&&<td><span className="process-badge status-active">{r.doc.launch_type==='automatic'?'⚙ Автоматично':'▷ Вручну'}</span></td>}<td>{r.latest&&r.doc.responsible_role?roleName(r.doc.responsible_role):directory.employees.find(e=>e.id===(r.owner_employee_id||r.doc.owner_employee_id))?.name||P.none}</td>{tab==='templates'?<><td>{r.doc.goal||r.doc.description||'—'}</td><td>{r.doc.stages.length}</td><td>{r.doc.stages.reduce((n,s)=>n+s.tasks.length,0)}</td><td>{dateLabel((r.latest.updated_at||r.latest.created_at||'').slice(0,10))}</td></>:<><td>{dateLabel(r.starts_on)}</td><td>{tab==='done'?dateLabel(end?.slice(0,10)):r.deadline?dateLabel(r.deadline):'—'}</td>{tab==='active'?<td><span>{progress}%</span><progress max="100" value={progress}/></td>:<><td>{end?Math.max(0,Math.ceil((new Date(end)-new Date(r.starts_on))/86400000)):0} дн.</td><td><span className="process-rating">★</span> {r.rating??'—'}</td></>}<td><span className={`process-badge status-${instanceStatus(r)}`}>{statuses[instanceStatus(r)]}</span></td></>}<td>{actions(r)}</td></tr>})}</tbody></table>{!rows.length&&<p>{P.empty}</p>}</div><p className="process-table-footer">Показано {rows.length} з {all.length} процесів</p></>
}
