import {useState} from 'react'
import Dialog from '../components/Dialog'
import DateTimeInput from '../components/DateTimeInput'
import {requiredRoles} from './model'
import {roleName} from '../admin/labels'
export default function ProcessLaunch({initial,people,context,directory,busy,run,onClose,onLaunched}){
 const [form,setForm]=useState({...initial,name:'',deadline:context.today,note:'',role_assignments:{}}),doc=initial.versions.find(v=>v.id===form.version_id).definition,roleBased=doc.schema_version===2
 const assignable=people.map(p=>({...directory.employees.find(e=>e.id===p.id),...p})).filter(p=>p.active!==false&&!p.archived),set=(k,v)=>setForm({...form,[k]:v})
 return <Dialog title="Запустити процес" {...{busy,onClose}}><form className="process-launch" onSubmit={async e=>{e.preventDefault();const {versions,...args}=form;void versions;const data=new FormData(e.currentTarget);args.starts_on=data.get('starts_on');args.deadline=data.get('deadline');if(!roleBased){delete args.role_assignments;delete args.name;delete args.deadline;delete args.note}if(await run('process_launch',args))onLaunched()}}><label>Версія<select value={form.version_id} onChange={e=>set('version_id',Number(e.target.value))}>{initial.versions.map(v=><option key={v.id} value={v.id}>Версія {v.number}</option>)}</select></label>{roleBased&&<label>Назва запуску<input required value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Наприклад: Філадельфія Mango"/></label>}<label>Дата початку<DateTimeInput type="date" name="starts_on" defaultValue={form.starts_on} required/></label>{roleBased&&<label>Дедлайн<DateTimeInput type="date" name="deadline" defaultValue={form.deadline} required/></label>}
 {roleBased?requiredRoles(doc).map(r=><label key={r}>{r===doc.responsible_role?'Відповідальний за процес':'Учасник'} · {roleName(r)}<select required value={form.role_assignments[r]||''} onChange={e=>set('role_assignments',{...form.role_assignments,[r]:Number(e.target.value)})}><option value="">Оберіть працівника</option>{assignable.filter(p=>p.role===r||p.production_role===r).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>):<><p>Це опублікована попередня версія. Збережено її початкові правила призначення.</p><label>Виконавець за замовчуванням<select value={form.default_employee_id} onChange={e=>set('default_employee_id',Number(e.target.value))}>{assignable.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><details><summary>Відповідальні за окремі завдання</summary>{doc.stages.flatMap(s=>s.tasks).map(t=><label key={t.key}>{t.title}<select value={form.assignments[t.key]||''} onChange={e=>{const next={...form.assignments};if(e.target.value)next[t.key]=Number(e.target.value);else delete next[t.key];set('assignments',next)}}><option value="">Із шаблону / за замовчуванням</option>{assignable.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>)}</details></>}
 <label>Відділ<select value={form.department_id||''} onChange={e=>set('department_id',Number(e.target.value)||null)}><option value="">Не призначено</option>{directory.departments.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Локація<select value={form.location_id||''} onChange={e=>set('location_id',Number(e.target.value)||null)}><option value="">Не призначено</option>{directory.locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{roleBased&&<label>Примітка<textarea value={form.note} onChange={e=>set('note',e.target.value)}/></label>}<label><input required type="checkbox"/>Підтверджую створення реальних завдань</label><button disabled={busy} className="primary">Запустити процес</button></form></Dialog>
}
