// Polish Orders dictionary; all new board copy lives here for a future locale.
export const labels = {
 urgencyFilters:{all:'Wszystkie',overdue:'Po czasie',urgent:'≤ 10 min',warning:'≤ 30 min',normal:'Pozostałe'}, urgencyFilter:'Pilność zamówień', actualPrep: value => `Czas przygotowania: ${value}`,
 myActive:'Moje aktywne', availableWork:'Do wzięcia', operatorBoard:'Operacyjna tablica zamówień',
 workMode:'Tryb pracy Zamówień', generalMode:'Tryb ogólny', operationalMode:'Tryb operacyjny',
 generatorTitle:'Generator zamówienia testowego', generatorHelp:'Wyłącznie fikcyjne zamówienia UAT. Wybieraj istniejące produkty; typ dotyczy tylko tej testowej pozycji.',
 type:'Typ pozycji', itemTypes:{product:'Produkt',set:'Zestaw',addon:'Dodatek',drink:'Napój'},
 line:n=>`Pozycja ${n}`, component:n=>`Komponent ${n}`, setName:'Nazwa zestawu', productName:'Produkt z katalogu', setCount:'Ilość zestawów', itemCount:'Ilość pozycji',
 removeLine:'Usuń pozycję', composition:'Skład zestawu', perSetHint:'Podaj ilości na jeden zestaw. Łączna ilość przelicza się automatycznie.',
 componentProduct:'Produkt komponentu', perSet:'Ilość na 1 zestaw', total:n=>`Łącznie: ${Number.isFinite(n)?n:0} szt.`,
 removeComponent:'Usuń komponent', addRoll:'+ Dodaj rolkę', addLine:'+ Dodaj pozycję', createOrder:'Utwórz zamówienie',
 searchProduct:'Szukaj produktu', chooseProduct:'Wybierz produkt', generatorInvalid:'Wybierz produkty z katalogu i dodatnie całkowite ilości. Zestaw musi mieć skład. Limit: 50 elementów, 10 000 szt. na element.',
 operationalStatus:'Status operacyjny', ready_to_issue:'Do wydania', viewOrder:'Zobacz zamówienie', closeNotice:'Zamknij i oznacz jako przeczytane',
 noticeShort:(type,number)=>`${number} · ${type==='DEADLINE_OVERDUE'?'po czasie':type==='DEADLINE_10'?'do wydania za 10 min':'do wydania za 30 min'}`,
 all: 'Wszystkie' , waiting: 'Oczekujące', working: 'W realizacji', done: 'Zakończone',
 wholeOrder: 'Weź całe zamówienie', selected: n => `Weź zaznaczone (${n})`,
 dispatch: 'Przekaż na kuchnię', start: 'Start', part: 'Weź część', allQuantity: 'Całość', other: 'Inna', take: 'Weź',
 wholeSet: 'Weź cały zestaw', setPart: (n,total) => `Weź ${n}/${total} zestawów`,
 left: 'Pozostało', issued: 'Wydane', units: 'szt.', visible: n => `Widoczne pozycje: ${n}`,
 readyAt: time => `Wydać o ${time}`, prep: n => `Przewidywany czas przygotowania ~${n} min`,
 overdue: n => `Po czasie · ${n} min`, warning: 'Do wydania ≤ 30 min', urgent: 'Pilne · do wydania ≤ 10 min',
 normal: 'Standardowo', empty: 'Brak zamówień w tym widoku.', expand: 'Rozwiń zestaw', collapse: 'Zwiń zestaw',
 select: name => `Zaznacz ${name}`, quantity: name => `Ilość — ${name}`,
 stages: { NEW:'Nowe', TO_DO:'Do zrobienia', IN_PROGRESS:'W trakcie', READY_FOR_CUTTING:'Do krojenia', CUTTING:'Krojenie', COMPLETED:'Wydane' },
 lifecycle: {new:'Oczekujące',partial:'Częściowo przejęte',in_progress:'W realizacji',done:'Zakończone'},
 ready: 'Gotowe', release: 'Oddaj zadanie', confirmRelease: 'Potwierdź oddanie', keep: 'Zostaw u mnie',
 cut: n => `Rozpocznij krojenie ×${n}`, cutDone: 'Zakończ krojenie', issue: 'Wydane',
 active: 'W TRAKCIE', cutting: 'KROJENIE', readyCut: 'DO KROJENIA', history:'Historia zamówienia',
 shiftNeeded: 'Rozpocznij zmianę, aby przejąć zadania.', board: 'Tablica zamówień', noticeTitle:'Uwaga dla su-chefa', dismiss:'Przeczytane',
 notice: (type,number) => type==='DEADLINE_OVERDUE' ? `Zamówienie ${number} jest po czasie.` : type==='DEADLINE_10' ? `Pilne: zamówienie ${number} do wydania za 10 min.` : `Uwaga: zamówienie ${number} do wydania za 30 min.`,
 noticesFailed: 'Nie udało się odświeżyć powiadomień. Ponowimy automatycznie.',
 readyInput:'Czas wydania (opcjonalnie)', prepInput:'Czas przygotowania w minutach (opcjonalnie)',
}
