// Synthetic existing-PROD schema, built from the checked-in schema-only audit.
// Does NOT run BASE or any fresh-database Auth migration. Contains no production rows.
import { readFile } from 'node:fs/promises'
const read = path => readFile(new URL(path, import.meta.url),'utf8')
const qi = x => '"'+x.replaceAll('"','""')+'"'
export async function productionFixture(sql) {
 const audit=JSON.parse(await read('../../docs/plan-items-schema-audit-result.json'))
 for(const t of audit.tables) {
  const columns=audit.columns.filter(c=>c.table===t.relname).map(c=>`${qi(c.column)} ${c.type}${c.column==='id'?' GENERATED BY DEFAULT AS IDENTITY':c.default?' DEFAULT '+c.default:''}${c.not_null?' NOT NULL':''}`)
  await sql(`CREATE TABLE public.${qi(t.relname)} (${columns.join(',')})`)
 }
 for(const c of [...audit.constraints].sort((a,b)=>Number(a.definition.startsWith('FOREIGN'))-Number(b.definition.startsWith('FOREIGN'))))
  await sql(`ALTER TABLE public.${c.table} ADD CONSTRAINT ${qi(c.name)} ${c.definition}`)
 for(const f of audit.functions) await sql(f.definition)
 // Bring the earlier checked-in audit up to the confirmed pre-Auth schema.
 await sql(await read('../../docs/plan-items-note-time-delete-migration.sql'))
 await sql(`ALTER TABLE public."Products" ADD COLUMN base_unit text CHECK(base_unit IN ('g','ml','szt.'));
 ALTER TABLE public."Recipe_ingredients" ADD COLUMN ingredient_unit text CHECK(ingredient_unit IN ('g','ml','szt.'));
 CREATE SCHEMA extensions; CREATE EXTENSION pgcrypto WITH SCHEMA extensions;`)
 await sql(await read('./legacy-employee-rpcs.sql'))
 for(const t of audit.tables) await sql(`ALTER TABLE public.${qi(t.relname)} ENABLE ROW LEVEL SECURITY; GRANT ALL ON public.${qi(t.relname)} TO anon,authenticated,service_role`)
 for(const p of audit.policies) await sql(`CREATE POLICY ${qi(p.policyname)} ON public.${qi(p.tablename)} FOR ${p.cmd} TO ${p.roles.map(qi).join(',')} USING (${p.qual})`)
 await sql('GRANT USAGE ON SCHEMA public,extensions TO anon,authenticated,service_role; GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO anon,authenticated,service_role; GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon,authenticated,service_role;')
}
