-- Application baseline before Auth, derived from before-auth-schema.sql (2026-09-23).
-- Schema snapshot SHA-256: 69f433dd73a2366ed3aefb6967ad1cc06c90503707806c25af51974d888e79e2
-- Fresh Supabase database only; no data, legacy PIN APIs/column, owners or platform objects.
-- Requires Supabase roles and supabase_realtime publication; local tests supply platform stubs.
-- Apply both subsequent Auth migrations before enabling application access.
BEGIN;
REVOKE CREATE ON SCHEMA public FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA public TO authenticated, service_role;
-- Supabase may supply permissive defaults. Harden objects created by this migration role,
-- including functions added by the subsequent Auth migrations.
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM PUBLIC, anon, authenticated;

CREATE TABLE "public"."Employees" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "role" "text",
    "location_id" bigint,
    "active" boolean DEFAULT true
);

CREATE TABLE "public"."Locations" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "external_id" "text",
    "name" "text",
    "city" "text",
    "active" boolean DEFAULT true
);

CREATE TABLE "public"."Plan_items" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "plan_id" bigint,
    "nazwa" "text",
    "ilosc" numeric,
    "jednostka" "text",
    "priorytet" "text" DEFAULT 'normalny'::"text",
    "gotowe" boolean DEFAULT false,
    "completed_at" timestamp with time zone,
    "started_at" timestamp with time zone,
    "employee_id" bigint,
    "product_external_id" bigint,
    "note" "text",
    "ready_time" time without time zone
);

CREATE TABLE "public"."Plans" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "plan_date" "date" NOT NULL,
    "status" "text" DEFAULT 'active'::"text",
    "location_id" bigint NOT NULL
);

CREATE TABLE "public"."Products" (
    "id" bigint NOT NULL,
    "external_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "gramatura" numeric NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "base_unit" "text",
    CONSTRAINT "products_base_unit_allowed" CHECK ((("base_unit" IS NULL) OR ("base_unit" = ANY (ARRAY['g'::"text", 'ml'::"text", 'szt.'::"text"]))))
);

CREATE TABLE "public"."Recipe_ingredients" (
    "id" bigint NOT NULL,
    "product_external_id" bigint NOT NULL,
    "ingredient_external_id" bigint NOT NULL,
    "ingredient_name" "text" NOT NULL,
    "netto" numeric,
    "brutto" numeric,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "ingredient_unit" "text",
    CONSTRAINT "recipe_ingredients_unit_allowed" CHECK ((("ingredient_unit" IS NULL) OR ("ingredient_unit" = ANY (ARRAY['g'::"text", 'ml'::"text", 'szt.'::"text"]))))
);

ALTER TABLE "public"."Employees" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Employees_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Locations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Locations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Plan_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Plan_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Plans" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Plans_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Products" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Products_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."Recipe_ingredients" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Recipe_ingredients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."Employees"
    ADD CONSTRAINT "Employees_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Locations"
    ADD CONSTRAINT "Locations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Plan_items"
    ADD CONSTRAINT "Plan_items_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Plans"
    ADD CONSTRAINT "Plans_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Products"
    ADD CONSTRAINT "Products_external_id_key" UNIQUE ("external_id");

ALTER TABLE ONLY "public"."Products"
    ADD CONSTRAINT "Products_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Recipe_ingredients"
    ADD CONSTRAINT "Recipe_ingredients_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."Plans"
    ADD CONSTRAINT "plans_location_date_unique" UNIQUE ("location_id", "plan_date");

ALTER TABLE ONLY "public"."Recipe_ingredients"
    ADD CONSTRAINT "recipe_product_ingredient_unique" UNIQUE ("product_external_id", "ingredient_external_id");

ALTER TABLE ONLY "public"."Employees"
    ADD CONSTRAINT "Employees_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."Locations"("id");

ALTER TABLE ONLY "public"."Plan_items"
    ADD CONSTRAINT "Plan_items_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "public"."Plans"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Plans"
    ADD CONSTRAINT "Plans_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."Locations"("id");

ALTER TABLE ONLY "public"."Plan_items"
    ADD CONSTRAINT "plan_items_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."Employees"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Plan_items"
    ADD CONSTRAINT "plan_items_product_external_id_fkey" FOREIGN KEY ("product_external_id") REFERENCES "public"."Products"("external_id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Recipe_ingredients"
    ADD CONSTRAINT "recipe_product_fk" FOREIGN KEY ("product_external_id") REFERENCES "public"."Products"("external_id") ON UPDATE CASCADE ON DELETE CASCADE;

CREATE UNIQUE INDEX "products_external_id_unique" ON "public"."Products" USING "btree" ("external_id");

CREATE INDEX "recipe_ingredients_product_idx" ON "public"."Recipe_ingredients" USING "btree" ("product_external_id");

CREATE FUNCTION "public"."add_plan_item"("p_requester_id" bigint, "p_plan_id" bigint, "p_nazwa" "text", "p_ilosc" numeric, "p_jednostka" "text", "p_priorytet" "text", "p_product_external_id" bigint DEFAULT NULL::bigint) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  v_role text;
  v_user_location_id bigint;
  v_plan_location_id bigint;
  v_item_id bigint;
BEGIN

  SELECT role, location_id
  INTO v_role, v_user_location_id
  FROM public."Employees"
  WHERE id = p_requester_id
    AND active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Brak dostępu';
  END IF;

  if v_role IS NULL OR v_role not in ('administrator', 'manager', 'su-chef') THEN
    RAISE EXCEPTION 'Nie masz uprawnień do dodawania pozycji';
  END IF;

  SELECT location_id
  INTO v_plan_location_id
  FROM public."Plans"
  WHERE id = p_plan_id
    and status = 'active' FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nie znaleziono aktywnego planu';
  END IF;

  IF v_role <> 'administrator'
     AND v_user_location_id IS DISTINCT FROM v_plan_location_id THEN
    RAISE EXCEPTION 'Nie masz uprawnień do tego lokalu';
  END IF;

  IF p_nazwa IS NULL OR trim(p_nazwa) = '' THEN
    RAISE EXCEPTION 'Nazwa jest wymagana';
  END IF;

  IF p_ilosc IS NULL OR p_ilosc <= 0 THEN
    RAISE EXCEPTION 'Ilość musi być większa od 0';
  END IF;

  IF p_jednostka NOT IN ('g', 'kg', 'ml', 'l', 'szt.') THEN
    RAISE EXCEPTION 'Nieprawidłowa jednostka';
  END IF;

  IF p_priorytet NOT IN ('normalny', 'wysoki', 'pilny') THEN
    RAISE EXCEPTION 'Nieprawidłowy priorytet';
  END IF;

  INSERT INTO public."Plan_items" (
    plan_id,
    product_external_id,
    nazwa,
    ilosc,
    jednostka,
    priorytet,
    gotowe
  )
  VALUES (
    p_plan_id,
    p_product_external_id,
    trim(p_nazwa),
    p_ilosc,
    p_jednostka,
    p_priorytet,
    false
  )
  RETURNING id INTO v_item_id;

  RETURN v_item_id;

END;
$$;

CREATE FUNCTION "public"."add_plan_item"("p_requester_id" bigint, "p_plan_id" bigint, "p_nazwa" "text", "p_ilosc" numeric, "p_jednostka" "text", "p_priorytet" "text", "p_product_external_id" bigint, "p_note" "text", "p_ready_time" time without time zone) RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  v_role text;
  v_user_location_id bigint;
  v_plan_location_id bigint;
  v_item_id bigint;
BEGIN

  SELECT role, location_id
  INTO v_role, v_user_location_id
  FROM public."Employees"
  WHERE id = p_requester_id
    AND active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Brak dostępu';
  END IF;

  if v_role IS NULL OR v_role not in ('administrator', 'manager', 'su-chef') THEN
    RAISE EXCEPTION 'Nie masz uprawnień do dodawania pozycji';
  END IF;

  SELECT location_id
  INTO v_plan_location_id
  FROM public."Plans"
  WHERE id = p_plan_id
    and status = 'active' FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nie znaleziono aktywnego planu';
  END IF;

  IF v_role <> 'administrator'
     AND v_user_location_id IS DISTINCT FROM v_plan_location_id THEN
    RAISE EXCEPTION 'Nie masz uprawnień do tego lokalu';
  END IF;

  IF p_nazwa IS NULL OR trim(p_nazwa) = '' THEN
    RAISE EXCEPTION 'Nazwa jest wymagana';
  END IF;

  IF p_ilosc IS NULL OR p_ilosc <= 0 THEN
    RAISE EXCEPTION 'Ilość musi być większa od 0';
  END IF;

  IF p_jednostka NOT IN ('g', 'kg', 'ml', 'l', 'szt.') THEN
    RAISE EXCEPTION 'Nieprawidłowa jednostka';
  END IF;

  IF p_priorytet NOT IN ('normalny', 'wysoki', 'pilny') THEN
    RAISE EXCEPTION 'Nieprawidłowy priorytet';
  END IF;

  INSERT INTO public."Plan_items" (
    plan_id,
    product_external_id,
    nazwa,
    ilosc,
    jednostka,
    priorytet,
    note,
    ready_time,
    gotowe
  )
  VALUES (
    p_plan_id,
    p_product_external_id,
    trim(p_nazwa),
    p_ilosc,
    p_jednostka,
    p_priorytet,
    NULLIF(btrim(p_note), ''),
    p_ready_time,
    false
  )
  RETURNING id INTO v_item_id;

  RETURN v_item_id;

END;
$$;

CREATE FUNCTION "public"."complete_plan_item"("p_requester_id" bigint, "p_item_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$BEGIN

  -- Dotyczy wszystkich ról. Brak lub inna data nie może uruchomić starego RPC.
  -- Blokada planu utrzymuje status/datę stabilne do końca operacji.
  PERFORM 1
  FROM public."Plans" AS date_guard_plan
  JOIN public."Plan_items" AS date_guard_item ON date_guard_item.plan_id = date_guard_plan.id
  WHERE date_guard_item.id = p_item_id
    AND date_guard_plan.plan_date = (now() AT TIME ZONE 'Europe/Warsaw')::date
  FOR UPDATE OF date_guard_plan;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Operacja jest dostępna wyłącznie dla planu na dziś' USING ERRCODE = '42501';
  END IF;


DECLARE
  v_user_location_id bigint;
  v_plan_location_id bigint;
  v_item_started_at timestamptz;
  v_item_gotowe boolean;
BEGIN

  -- Sprawdzamy pracownika
  SELECT e.location_id
  INTO v_user_location_id
  FROM public."Employees" e
  WHERE e.id = p_requester_id
    AND e.active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Brak dostępu';
  END IF;

  IF v_user_location_id IS NULL THEN
    RAISE EXCEPTION 'Pracownik nie jest przypisany do lokalu';
  END IF;

  -- Sprawdzamy pozycję + aktywny plan
  SELECT
    p.location_id,
    pi.started_at,
    COALESCE(pi.gotowe, false)
  INTO
    v_plan_location_id,
    v_item_started_at,
    v_item_gotowe
  FROM public."Plan_items" pi
  JOIN public."Plans" p
    ON p.id = pi.plan_id
  WHERE pi.id = p_item_id
    AND p.status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nie znaleziono pozycji w aktywnym planie';
  END IF;

  -- Tylko własny lokal
  IF v_user_location_id IS DISTINCT FROM v_plan_location_id THEN
    RAISE EXCEPTION 'Nie masz uprawnień do tego lokalu';
  END IF;

  -- Musi być wcześniej rozpoczęta
  IF v_item_started_at IS NULL THEN
    RAISE EXCEPTION 'Najpierw rozpocznij pracę';
  END IF;

  IF v_item_gotowe THEN
    RAISE EXCEPTION 'Ta pozycja jest już zakończona';
  END IF;

  -- WAŻNE:
  -- employee_id pochodzi z requester_id.
  -- Frontend nie może wskazać innego pracownika.
  UPDATE public."Plan_items"
  SET
    gotowe = true,
    completed_at = now(),
    employee_id = p_requester_id
  WHERE id = p_item_id;

END;
END;
$$;

CREATE FUNCTION "public"."complete_production_plan"("p_requester_id" bigint, "p_plan_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
declare
  v_role text;
  v_user_location_id bigint;
  v_plan_location_id bigint;
begin

  -- Sprawdzamy pracownika
  select role, location_id
  into v_role, v_user_location_id
  from public."Employees"
  where id = p_requester_id
    and active = true;

  if not found then
    raise exception 'Brak dostępu';
  end if;

  -- Employee nie może kończyć całego planu
  if v_role not in ('administrator', 'manager', 'su-chef') then
    raise exception 'Nie masz uprawnień do zakończenia planu';
  end if;

  -- Sprawdzamy lokal planu
  select location_id
  into v_plan_location_id
  from public."Plans"
  where id = p_plan_id
    and status = 'active';

  if not found then
    raise exception 'Nie znaleziono aktywnego planu';
  end if;

  -- Manager i su-chef tylko w swoim lokalu
  if v_role <> 'administrator'
     and v_user_location_id <> v_plan_location_id then
    raise exception 'Nie masz uprawnień do tego lokalu';
  end if;

  -- Kończymy plan
  update public."Plans"
  set status = 'completed'
  where id = p_plan_id;

end;
$$;

CREATE FUNCTION "public"."create_production_plan"("p_requester_id" bigint, "p_location_id" bigint, "p_plan_date" "date", "p_items" "jsonb") RETURNS bigint
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
declare
  v_role text;
  v_user_location_id bigint;
  v_plan_id bigint;
begin

  select role, location_id
  into v_role, v_user_location_id
  from public."Employees"
  where id = p_requester_id
    and active = true;

  if not found then
    raise exception 'Brak dostępu';
  end if;

  if v_role IS NULL OR v_role not in ('administrator', 'manager', 'su-chef') then
    raise exception 'Nie masz uprawnień do tworzenia planu';
  end if;

  if v_role <> 'administrator'
     and v_user_location_id IS DISTINCT FROM p_location_id then
    raise exception 'Nie masz uprawnień do tego lokalu';
  end if;

  insert into public."Plans" (
    plan_date,
    status,
    location_id
  )
  values (
    p_plan_date,
    'active',
    p_location_id
  )
  returning id into v_plan_id;

  insert into public."Plan_items" (
    plan_id,
    product_external_id,
    nazwa,
    ilosc,
    jednostka,
    priorytet,
    note,
    ready_time,
    gotowe
  )
  select
    v_plan_id,
    x.product_external_id,
    x.nazwa,
    x.ilosc,
    x.jednostka,
    x.priorytet,
    NULLIF(btrim(x.note), ''),
    x.ready_time,
    false
  from jsonb_to_recordset(p_items) as x(
    product_external_id bigint,
    nazwa text,
    ilosc numeric,
    jednostka text,
    priorytet text,
    note text,
    ready_time time without time zone
  );

  return v_plan_id;

end;
$$;

CREATE FUNCTION "public"."delete_plan_item"("p_requester_id" bigint, "p_item_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  v_role text;
  v_user_location_id bigint;

  v_plan_location_id bigint;
  v_started_at timestamptz;
  v_gotowe boolean;
  v_completed_at timestamptz;
  v_employee_id bigint;
BEGIN

  -- Kto wykonuje operację?
  SELECT
    e.role,
    e.location_id
  INTO
    v_role,
    v_user_location_id
  FROM public."Employees" e
  WHERE e.id = p_requester_id
    AND e.active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Brak dostępu';
  END IF;

  -- Tylko administrator, manager i su-chef
  if v_role IS NULL OR v_role not in ('administrator', 'manager', 'su-chef') THEN
    RAISE EXCEPTION 'Nie masz uprawnień do usuwania pozycji';
  END IF;

  PERFORM 1 FROM public."Plans" p
  JOIN public."Plan_items" pi ON pi.plan_id = p.id
  WHERE pi.id = p_item_id FOR UPDATE OF p;

  -- Pobieramy pozycję i jej plan
  SELECT
    p.location_id,
    pi.started_at,
    pi.completed_at,
    pi.employee_id,
    COALESCE(pi.gotowe, false)
  INTO
    v_plan_location_id,
    v_started_at,
    v_completed_at,
    v_employee_id,
    v_gotowe
  FROM public."Plan_items" pi
  JOIN public."Plans" p
    ON p.id = pi.plan_id
  WHERE pi.id = p_item_id
    AND p.status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nie znaleziono pozycji w aktywnym planie';
  END IF;

  -- Manager i su-chef tylko w swoim lokalu
  IF v_role <> 'administrator'
     AND v_user_location_id IS DISTINCT FROM v_plan_location_id THEN
    RAISE EXCEPTION 'Nie masz uprawnień do tego lokalu';
  END IF;

  -- Rozpoczętej pracy nie wolno usuwać
  IF v_started_at IS NOT NULL OR v_completed_at IS NOT NULL OR v_employee_id IS NOT NULL THEN
    RAISE EXCEPTION 'Nie można usunąć rozpoczętej pozycji';
  END IF;

  -- Gotowej pozycji tym bardziej nie usuwamy
  IF v_gotowe THEN
    RAISE EXCEPTION 'Nie można usunąć zakończonej pozycji';
  END IF;

  DELETE FROM public."Plan_items"
  WHERE id = p_item_id;

END;
$$;

CREATE FUNCTION "public"."delete_production_plan"("p_requester_id" bigint, "p_plan_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  requester public."Employees"%ROWTYPE;
  target_plan public."Plans"%ROWTYPE;
BEGIN
  SELECT * INTO requester FROM public."Employees"
    WHERE id = p_requester_id AND active = true FOR SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nieaktywny lub nieistniejący pracownik' USING ERRCODE = '42501';
  END IF;
  IF requester.role IS NULL OR requester.role NOT IN ('administrator', 'manager', 'su-chef') THEN
    RAISE EXCEPTION 'Brak uprawnień do usuwania planu' USING ERRCODE = '42501';
  END IF;
  -- Ta sama blokada co w audytowanych start_plan_item/complete_plan_item.
  SELECT * INTO target_plan FROM public."Plans" WHERE id = p_plan_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Plan nie istnieje' USING ERRCODE = 'P0002';
  END IF;
  IF requester.role <> 'administrator' AND
    (requester.location_id IS NULL OR requester.location_id IS DISTINCT FROM target_plan.location_id) THEN
    RAISE EXCEPTION 'Brak uprawnień do tego lokalu' USING ERRCODE = '42501';
  END IF;
  IF target_plan.status IS DISTINCT FROM 'active' OR EXISTS (
    SELECT 1 FROM public."Plan_items" WHERE plan_id = p_plan_id AND
      (started_at IS NOT NULL OR completed_at IS NOT NULL OR gotowe IS TRUE OR employee_id IS NOT NULL)
  ) THEN
    RAISE EXCEPTION 'Nie można usunąć rozpoczętego lub zakończonego planu. Historia pozostaje zachowana.' USING ERRCODE = '55000';
  END IF;
  DELETE FROM public."Plans" WHERE id = p_plan_id;
END;
$$;

CREATE FUNCTION "public"."reopen_production_plan"("p_requester_id" bigint, "p_plan_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  requester public."Employees"%ROWTYPE;
  target_plan public."Plans"%ROWTYPE;
BEGIN
  SELECT * INTO requester FROM public."Employees"
    WHERE id = p_requester_id AND active = true
    FOR SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nieaktywny lub nieistniejący pracownik' USING ERRCODE = '42501';
  END IF;
  IF requester.role IS NULL OR requester.role NOT IN ('administrator', 'manager', 'su-chef') THEN
    RAISE EXCEPTION 'Brak uprawnień do wznowienia planu' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO target_plan FROM public."Plans" WHERE id = p_plan_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Plan nie istnieje' USING ERRCODE = 'P0002';
  END IF;
  IF requester.role <> 'administrator' AND
    (requester.location_id IS NULL OR requester.location_id IS DISTINCT FROM target_plan.location_id) THEN
    RAISE EXCEPTION 'Brak uprawnień do tego lokalu' USING ERRCODE = '42501';
  END IF;
  IF target_plan.status IS DISTINCT FROM 'completed' THEN
    RAISE EXCEPTION 'Wznowić można wyłącznie zakończony plan' USING ERRCODE = '55000';
  END IF;

  UPDATE public."Plans" SET status = 'active' WHERE id = p_plan_id;
  -- Żadnych operacji na Plan_items ani innych polach Plans.
END;
$$;

CREATE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE FUNCTION "public"."start_plan_item"("p_requester_id" bigint, "p_item_id" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$BEGIN

  -- Dotyczy wszystkich ról. Brak lub inna data nie może uruchomić starego RPC.
  -- Blokada planu utrzymuje status/datę stabilne do końca operacji.
  PERFORM 1
  FROM public."Plans" AS date_guard_plan
  JOIN public."Plan_items" AS date_guard_item ON date_guard_item.plan_id = date_guard_plan.id
  WHERE date_guard_item.id = p_item_id
    AND date_guard_plan.plan_date = (now() AT TIME ZONE 'Europe/Warsaw')::date
  FOR UPDATE OF date_guard_plan;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Operacja jest dostępna wyłącznie dla planu na dziś' USING ERRCODE = '42501';
  END IF;


DECLARE
  v_user_location_id bigint;
  v_plan_location_id bigint;
  v_item_started_at timestamptz;
  v_item_gotowe boolean;
BEGIN

  -- Sprawdzamy pracownika
  SELECT e.location_id
  INTO v_user_location_id
  FROM public."Employees" e
  WHERE e.id = p_requester_id
    AND e.active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Brak dostępu';
  END IF;

  -- Pracownik musi być przypisany do lokalu
  IF v_user_location_id IS NULL THEN
    RAISE EXCEPTION 'Pracownik nie jest przypisany do lokalu';
  END IF;

  -- Sprawdzamy pozycję + aktywny plan
  SELECT
    p.location_id,
    pi.started_at,
    COALESCE(pi.gotowe, false)
  INTO
    v_plan_location_id,
    v_item_started_at,
    v_item_gotowe
  FROM public."Plan_items" pi
  JOIN public."Plans" p
    ON p.id = pi.plan_id
  WHERE pi.id = p_item_id
    AND p.status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nie znaleziono pozycji w aktywnym planie';
  END IF;

  -- Tylko własny lokal
  IF v_user_location_id IS DISTINCT FROM v_plan_location_id THEN
    RAISE EXCEPTION 'Nie masz uprawnień do tego lokalu';
  END IF;

  -- Nie uruchamiamy ponownie zakończonego zadania
  IF v_item_gotowe THEN
    RAISE EXCEPTION 'Ta pozycja jest już zakończona';
  END IF;

  -- Nie resetujemy czasu przez ponowne kliknięcie
  IF v_item_started_at IS NOT NULL THEN
    RAISE EXCEPTION 'Ta pozycja jest już w trakcie pracy';
  END IF;

  UPDATE public."Plan_items"
  SET
    started_at = now(),
    completed_at = NULL,
    gotowe = false
  WHERE id = p_item_id;

END;
END;
$$;

CREATE FUNCTION "public"."update_plan_item"("p_requester_id" bigint, "p_item_id" bigint, "p_nazwa" "text", "p_ilosc" numeric, "p_jednostka" "text", "p_priorytet" "text", "p_product_external_id" bigint DEFAULT NULL::bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  v_role text;
  v_user_location_id bigint;
  v_plan_location_id bigint;
  v_started_at timestamptz;
  v_gotowe boolean;
  v_completed_at timestamptz;
  v_employee_id bigint;
BEGIN

  SELECT e.role, e.location_id
  INTO v_role, v_user_location_id
  FROM public."Employees" e
  WHERE e.id = p_requester_id
    AND e.active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Brak dostępu';
  END IF;

  if v_role IS NULL OR v_role not in ('administrator', 'manager', 'su-chef') THEN
    RAISE EXCEPTION 'Nie masz uprawnień do edycji pozycji';
  END IF;

  PERFORM 1 FROM public."Plans" p
  JOIN public."Plan_items" pi ON pi.plan_id = p.id
  WHERE pi.id = p_item_id FOR UPDATE OF p;

  SELECT
    p.location_id,
    pi.started_at,
    pi.completed_at,
    pi.employee_id,
    COALESCE(pi.gotowe, false)
  INTO
    v_plan_location_id,
    v_started_at,
    v_completed_at,
    v_employee_id,
    v_gotowe
  FROM public."Plan_items" pi
  JOIN public."Plans" p
    ON p.id = pi.plan_id
  WHERE pi.id = p_item_id
    AND p.status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nie znaleziono pozycji w aktywnym planie';
  END IF;

  IF v_role <> 'administrator'
     AND v_user_location_id IS DISTINCT FROM v_plan_location_id THEN
    RAISE EXCEPTION 'Nie masz uprawnień do tego lokalu';
  END IF;

  IF v_started_at IS NOT NULL OR v_completed_at IS NOT NULL OR v_employee_id IS NOT NULL OR v_gotowe THEN
    RAISE EXCEPTION 'Nie można edytować rozpoczętej pozycji';
  END IF;

  IF p_nazwa IS NULL OR trim(p_nazwa) = '' THEN
    RAISE EXCEPTION 'Nazwa jest wymagana';
  END IF;

  IF p_ilosc IS NULL OR p_ilosc <= 0 THEN
    RAISE EXCEPTION 'Ilość musi być większa od 0';
  END IF;

  IF p_jednostka NOT IN ('g', 'kg', 'ml', 'l', 'szt.') THEN
    RAISE EXCEPTION 'Nieprawidłowa jednostka';
  END IF;

  IF p_priorytet NOT IN ('normalny', 'wysoki', 'pilny') THEN
    RAISE EXCEPTION 'Nieprawidłowy priorytet';
  END IF;

  UPDATE public."Plan_items"
  SET
    product_external_id = p_product_external_id,
    nazwa = trim(p_nazwa),
    ilosc = p_ilosc,
    jednostka = p_jednostka,
    priorytet = p_priorytet
  WHERE id = p_item_id;

END;
$$;

CREATE FUNCTION "public"."update_plan_item"("p_requester_id" bigint, "p_item_id" bigint, "p_nazwa" "text", "p_ilosc" numeric, "p_jednostka" "text", "p_priorytet" "text", "p_product_external_id" bigint, "p_note" "text", "p_ready_time" time without time zone) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
DECLARE
  v_role text;
  v_user_location_id bigint;
  v_plan_location_id bigint;
  v_started_at timestamptz;
  v_gotowe boolean;
  v_completed_at timestamptz;
  v_employee_id bigint;
BEGIN

  SELECT e.role, e.location_id
  INTO v_role, v_user_location_id
  FROM public."Employees" e
  WHERE e.id = p_requester_id
    AND e.active = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Brak dostępu';
  END IF;

  if v_role IS NULL OR v_role not in ('administrator', 'manager', 'su-chef') THEN
    RAISE EXCEPTION 'Nie masz uprawnień do edycji pozycji';
  END IF;

  PERFORM 1 FROM public."Plans" p
  JOIN public."Plan_items" pi ON pi.plan_id = p.id
  WHERE pi.id = p_item_id FOR UPDATE OF p;

  SELECT
    p.location_id,
    pi.started_at,
    pi.completed_at,
    pi.employee_id,
    COALESCE(pi.gotowe, false)
  INTO
    v_plan_location_id,
    v_started_at,
    v_completed_at,
    v_employee_id,
    v_gotowe
  FROM public."Plan_items" pi
  JOIN public."Plans" p
    ON p.id = pi.plan_id
  WHERE pi.id = p_item_id
    AND p.status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nie znaleziono pozycji w aktywnym planie';
  END IF;

  IF v_role <> 'administrator'
     AND v_user_location_id IS DISTINCT FROM v_plan_location_id THEN
    RAISE EXCEPTION 'Nie masz uprawnień do tego lokalu';
  END IF;

  IF v_started_at IS NOT NULL OR v_completed_at IS NOT NULL OR v_employee_id IS NOT NULL OR v_gotowe THEN
    RAISE EXCEPTION 'Nie można edytować rozpoczętej pozycji';
  END IF;

  IF p_nazwa IS NULL OR trim(p_nazwa) = '' THEN
    RAISE EXCEPTION 'Nazwa jest wymagana';
  END IF;

  IF p_ilosc IS NULL OR p_ilosc <= 0 THEN
    RAISE EXCEPTION 'Ilość musi być większa od 0';
  END IF;

  IF p_jednostka NOT IN ('g', 'kg', 'ml', 'l', 'szt.') THEN
    RAISE EXCEPTION 'Nieprawidłowa jednostka';
  END IF;

  IF p_priorytet NOT IN ('normalny', 'wysoki', 'pilny') THEN
    RAISE EXCEPTION 'Nieprawidłowy priorytet';
  END IF;

  UPDATE public."Plan_items"
  SET
    product_external_id = p_product_external_id,
    nazwa = trim(p_nazwa),
    ilosc = p_ilosc,
    jednostka = p_jednostka,
    priorytet = p_priorytet,
    note = NULLIF(btrim(p_note), ''),
    ready_time = p_ready_time
  WHERE id = p_item_id;

END;
$$;

CREATE FUNCTION "public"."update_production_plan"("p_requester_id" bigint, "p_plan_id" bigint, "p_items" "jsonb") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'pg_catalog'
    AS $$
declare
  v_role text;
  v_user_location_id bigint;
  v_plan_location_id bigint;
begin

  select role, location_id
  into v_role, v_user_location_id
  from public."Employees"
  where id = p_requester_id
    and active = true;

  if not found then
    raise exception 'Brak dostępu';
  end if;

  if v_role IS NULL OR v_role not in ('administrator', 'manager', 'su-chef') then
    raise exception 'Nie masz uprawnień do edycji planu';
  end if;

  select location_id
  into v_plan_location_id
  from public."Plans"
  where id = p_plan_id
    and status = 'active' FOR UPDATE;

  if not found then
    raise exception 'Nie znaleziono aktywnego planu';
  end if;

  if v_role <> 'administrator'
     and v_user_location_id IS DISTINCT FROM v_plan_location_id then
    raise exception 'Nie masz uprawnień do tego lokalu';
  end if;

  -- Nie wolno usunąć śladów produkcji przez zbiorczą edycję.
  IF EXISTS (SELECT 1 FROM public."Plan_items" WHERE plan_id = p_plan_id
    AND (started_at IS NOT NULL OR completed_at IS NOT NULL OR gotowe IS TRUE OR employee_id IS NOT NULL)) THEN
    RAISE EXCEPTION 'Nie można zastąpić pozycji rozpoczętego planu' USING ERRCODE = '55000';
  END IF;

  delete from public."Plan_items"
  where plan_id = p_plan_id;

  insert into public."Plan_items" (
    plan_id,
    product_external_id,
    nazwa,
    ilosc,
    jednostka,
    priorytet,
    note,
    ready_time,
    gotowe
  )
  select
    p_plan_id,
    x.product_external_id,
    x.nazwa,
    x.ilosc,
    x.jednostka,
    x.priorytet,
    NULLIF(btrim(x.note), ''),
    x.ready_time,
    false
  from jsonb_to_recordset(p_items) as x(
    product_external_id bigint,
    nazwa text,
    ilosc numeric,
    jednostka text,
    priorytet text,
    note text,
    ready_time time without time zone
  );

end;
$$;

CREATE OR REPLACE TRIGGER "products_set_updated_at" BEFORE UPDATE ON "public"."Products" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

CREATE OR REPLACE TRIGGER "recipe_ingredients_set_updated_at" BEFORE UPDATE ON "public"."Recipe_ingredients" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- No client policies or client grants until Auth. service_role is server-only.
DO $$
DECLARE t text; f record;
BEGIN
  FOREACH t IN ARRAY ARRAY['Employees','Locations','Plans','Plan_items','Products','Recipe_ingredients'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon, authenticated', t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.%I TO service_role', t);
    EXECUTE format('REVOKE ALL ON SEQUENCE public.%I FROM PUBLIC, anon, authenticated', t || '_id_seq');
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE public.%I TO service_role', t || '_id_seq');
  END LOOP;
  FOR f IN SELECT p.oid::regprocedure AS signature FROM pg_proc p
    JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'
    AND p.proname = ANY(ARRAY['create_production_plan','update_production_plan',
      'complete_production_plan','reopen_production_plan','delete_production_plan',
      'add_plan_item','update_plan_item','delete_plan_item','start_plan_item',
      'complete_plan_item','set_updated_at'])
  LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated', f.signature);
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role', f.signature);
  END LOOP;
END $$;

-- Required by src/App.jsx subscriptions; do not create/replace the managed publication.
ALTER PUBLICATION supabase_realtime ADD TABLE ONLY public."Plan_items";
COMMIT;
